/*---------------------------------------------------------------------------------------------
 *  Copyright (c) OpenIDE. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/** Shared orientation for MCP initialization, lifecycle hooks and intent-based help. */
export const OPENIDE_CAPABILITY_CATALOG = [
	{ id: 'canvas', intents: ['Create a wireframe or interactive prototype', 'Design a mobile app, mockup, slides or visual document', 'Draw a whiteboard, animate shapes or model a 3D scene', 'Import images or design tokens and export PDF, PowerPoint, SVG or OBJ'], entryTools: ['openide_canvas_templates', 'openide_canvas_create', 'openide_canvas_inspect'], prefix: 'openide_canvas_', purpose: 'Create and edit Canvas designs in the IDE.', guidance: 'Inspect node IDs and revision before patching. Mutations pass IDE approval. Import workspace assets/tokens with canvas_import. Export HTML, PDF, PPTX, animated SVG or OBJ, or prepare an implementation handoff when ready.', requires: 'An open workspace and permission for mutations.' },
	{ id: 'browser', intents: ['Inspect the screen or preview already open in the IDE', 'Check a button, layout, animation or browser error'], entryTools: ['openide_browser_snapshot', 'openide_browser_screenshot', 'openide_browser_open'], prefix: 'openide_browser_', purpose: "Inspect and drive the user's live browser in OpenIDE for UI bugs and visual checks.", guidance: 'Use screenshots for appearance; visual checks measure defects. Record short flows for motion: start, actions, stop; inspect the contact sheet and findings before concluding.', requires: 'An available OpenIDE browser; allowed hosts and client permissions still apply.' },
	{ id: 'map', intents: ['Explain how this project is organized', 'Find what depends on this code or what a change affects'], entryTools: ['openide_project_map_query'], prefix: 'openide_project_map_', purpose: 'Find architecture, dependencies and change impact in Project Map.', guidance: 'Query the derived graph before broad source searches. Verify stale evidence against source; the graph is not authored memory.', requires: 'A workspace with its code index enabled.' },
	{ id: 'memory', intents: ['Recall an earlier decision or previous work', 'Remember a durable project finding or prepare a handoff'], entryTools: ['openide_memory_search', 'openide_memory_get', 'openide_memory_save', 'openide_memory_session_summary'], prefix: 'openide_memory', purpose: 'Recall prior decisions and save durable knowledge shared across IDE and CLI sessions.', guidance: 'Search, then get relevant notes. Before updating, get the current revision/hash. Save durable topics as canonical .openide/memory/notes/*.md; use session_summary for handoffs. MEMORY.md is the compatibility overview. Only a successful save receipt proves persistence; external agents own checkpoint timing.', requires: 'A trusted workspace; writing must be enabled. Forget only on an explicit user request.' },
	{ id: 'plans', intents: ['Prepare a plan I can edit and approve in the IDE'], entryTools: ['openide_plan_save'], prefix: 'openide_plan_', purpose: 'Prepare a plan the user can edit and review in OpenIDE.', guidance: 'plan_save blocks for a decision. Execute the returned edited plan only when approved; a discarded plan authorizes no execution.', requires: 'A workspace and a user decision.' },
	{ id: 'goals', intents: ['Check progress toward my objective', 'Report a goal milestone or blocker'], entryTools: ['openide_goal_get', 'openide_goal_report'], prefix: 'openide_goal_', purpose: 'Read persistent goals and record progress in their REPORT.md.', guidance: 'Read goal_get before reporting; external callers must select goal_id. Reports are unverified and cannot complete a goal. OpenIDE owns continuation; do not start a second provider /goal loop.', requires: 'A goal loaded in this window. Automatic continuation requires a verified structured adapter; other CLIs use manual tracking.' },
	{ id: 'editor', intents: ['Inspect my selection, open files or current editor errors'], entryTools: ['getCurrentSelection', 'getOpenEditors', 'getDiagnostics'], prefix: '', purpose: 'Read live editor selection and language diagnostics.', guidance: 'Use getCurrentSelection, getOpenEditors and getDiagnostics for editor context.', requires: 'The corresponding compatibility tool must be listed.' },
] as const;

export const OPENIDE_CAPABILITY_INSTRUCTIONS = 'This MCP server belongs to the OpenIDE window and workspace hosting your CLI. Match user intent to tools. For "look at this screen", preview, layout or button problems, inspect the live browser with openide_browser_snapshot, then screenshot/DOM/console as needed. Other browser plugins have separate inventories: an empty inventory there says nothing about the OpenIDE preview. For architecture, dependencies or change impact, use openide_project_map_query and verify stale evidence against source. For prior decisions, memory_search then memory_get; save durable findings with memory_save after checking revision/hash. Canonical notes are .openide/memory/notes/*.md; MEMORY.md is an overview. Only a successful save receipt proves persistence. For an editable plan, plan_save waits for review: execute the returned plan only if approved. For objective progress, goal_get then goal_report with goal_id; reporting does not verify or complete a goal. OpenIDE owns goal continuation; do not start another /goal loop. For editor context, read selection, open editors or diagnostics. Discover the OpenIDE tool names exposed by your client (including deferred tool search); openide_capabilities lists registered families, entry points and prerequisites. Check that inventory before concluding a capability is unavailable. For wireframes/prototypes, use canvas_templates. Use relevant tools; workspace and permission limits apply.';

/** A discoverable entry point even when the client defers the rest of the MCP catalogue. */
export const OPENIDE_CAPABILITY_DESCRIPTION = 'Discover the tools of the OpenIDE window hosting this CLI. Start here when the user asks to inspect their screen or embedded browser, recall or save project decisions, understand code dependencies, review a plan or goal progress, or read editor errors. Returns available tool names, natural-language use cases, entry points and prerequisites. Other browser plugins do not enumerate the OpenIDE preview. Read-only; does not run the tools.';

/** Registration is observable; runtime prerequisites must still be checked by the actual tool. */
export function openideCapabilityHelp(tools: readonly string[], family?: string): object {
	return {
		version: 1,
		families: OPENIDE_CAPABILITY_CATALOG.filter(entry => !family || entry.id === family).map(entry => {
			const names = tools.filter(name => entry.prefix ? name.startsWith(entry.prefix) : ['getCurrentSelection', 'getLatestSelection', 'getOpenEditors', 'getDiagnostics'].includes(name));
			return { ...entry, entryTools: entry.entryTools.filter(name => names.includes(name)), availability: names.length ? 'registered; runtime prerequisites apply' : 'not registered', tools: names };
		}),
	};
}
