#!/usr/bin/env bash
#
# Packages OpenIDE's Linux product into an AppImage.
# Requiere un build previo:  . dev/build.sh   (genera VSCode-linux-x64/).
#
# On NixOS it re-executes itself inside the FHS wrapper (result-fhs) because the downloaded
# appimagetool is an ELF that needs /lib64/ld-linux-x86-64.so.2,
# inexistente fuera del FHS.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --- NixOS: re-ejecutar dentro del FHS si falta el dynamic loader ------------
# appimagetool (an AppImage/ELF) needs glibc's loader, and it also invokes
# `file` and `mksquashfs`. The FHS wrapper provides all three.
#
# NO alcanza con chequear que /lib64/ld-linux-x86-64.so.2 exista: NixOS instala
# there is a nix-ld stub there that exists and is executable but aborts with "cannot run
# dynamically linked executables". With the previous guard the script stayed outside the
# sandbox and appimagetool died with "file command is missing".
# So we check the loader actually RUNS (--version exits 0; the stub exits 127).
needs_fhs="no"
/lib64/ld-linux-x86-64.so.2 --version > /dev/null 2>&1 || needs_fhs="yes"
command -v file > /dev/null 2>&1 || needs_fhs="yes"
command -v mksquashfs > /dev/null 2>&1 || needs_fhs="yes"

if [[ "${needs_fhs}" == "yes" ]]; then
	# The flag stops the recursion: if something is still missing inside the FHS, it is
	# reported instead of re-executing forever.
	if [[ -n "${OPENIDE_IN_FHS:-}" ]]; then
		echo "Ya estoy dentro del FHS y siguen faltando el loader de glibc, 'file' o 'mksquashfs'." >&2
		echo "Revisá los paquetes de dev/openide-fhs.nix y regenerá el wrapper." >&2
		exit 1
	fi
	FHS="${OPENIDE_FHS:-${ROOT_DIR}/result-fhs/bin/openide-build}"
	if [[ -x "${FHS}" ]]; then
		exec env OPENIDE_IN_FHS=1 "${FHS}" -c "cd '${ROOT_DIR}' && bash '${ROOT_DIR}/dev/build-appimage.sh'"
	fi
	echo "NixOS: falta el toolchain del AppImage y no encuentro el wrapper FHS." >&2
	echo "Crealo con:  nix-build dev/openide-fhs.nix -o result-fhs" >&2
	exit 1
fi

PRODUCT_DIR="${PRODUCT_DIR:-${ROOT_DIR}/VSCode-linux-x64}"
VERSION="${RELEASE_VERSION:-$(jq -er '.version' "${ROOT_DIR}/openide-version.json")}"
WORK_DIR="${ROOT_DIR}/.build/openide-appimage"
APP_DIR="${WORK_DIR}/OpenIDE.AppDir"
OUTPUT_DIR="${ROOT_DIR}/assets"
ARCH="${APPIMAGE_ARCH:-x86_64}"
OUTPUT_FILE="${OUTPUT_DIR}/OpenIDE-${VERSION}-${ARCH}.AppImage"
CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/openide-build"
# Override: APPIMAGETOOL_BIN=/ruta/appimagetool-x86_64.AppImage  (para builds
# reproducible builds vendor your own verified copy; see the AppImage repo's README).
APPIMAGETOOL="${APPIMAGETOOL_BIN:-${CACHE_DIR}/appimagetool-x86_64.AppImage}"

if [[ ! -x "${PRODUCT_DIR}/openide" ]]; then
	echo "No se encontró el producto Linux en ${PRODUCT_DIR}. Ejecutá primero: . dev/build.sh" >&2
	exit 1
fi

rm -rf "${APP_DIR}"
mkdir -p \
	"${APP_DIR}/usr/bin" \
	"${APP_DIR}/usr/share/openide" \
	"${APP_DIR}/usr/share/applications" \
	"${OUTPUT_DIR}" \
	"${CACHE_DIR}"

# --- Producto + symlink de CLI ----------------------------------------------
cp -a "${PRODUCT_DIR}/." "${APP_DIR}/usr/share/openide/"
ln -s ../share/openide/openide "${APP_DIR}/usr/bin/openide"

# --- hicolor icon at its real resolution + .DirIcon -------------------------
# The source may not be 512x512 (this build is 1024x1024): it goes into the hicolor dir
# matching its real resolution and, when imagemagick is available, the smaller sizes are
# generated by downscaling.
SOURCE_ICON="${PRODUCT_DIR}/resources/app/resources/linux/code.png"
ICON_RES="1024x1024"
if command -v identify >/dev/null 2>&1; then
	w=$(identify -format '%w' "${SOURCE_ICON}" 2>/dev/null || echo 1024)
	h=$(identify -format '%h' "${SOURCE_ICON}" 2>/dev/null || echo 1024)
	ICON_RES="${w}x${h}"
fi
mkdir -p "${APP_DIR}/usr/share/icons/hicolor/${ICON_RES}/apps"
cp "${SOURCE_ICON}" "${APP_DIR}/usr/share/icons/hicolor/${ICON_RES}/apps/openide.png"
if command -v convert >/dev/null 2>&1; then
	for size in 512 256 128 64 48 32; do
		mkdir -p "${APP_DIR}/usr/share/icons/hicolor/${size}x${size}/apps"
		convert "${SOURCE_ICON}" -resize "${size}x${size}" \
			"${APP_DIR}/usr/share/icons/hicolor/${size}x${size}/apps/openide.png" 2>/dev/null || true
	done
fi
# the AppDir's root icon + .DirIcon (appimagetool uses them for the thumbnail)
cp "${SOURCE_ICON}" "${APP_DIR}/openide.png"
cp "${SOURCE_ICON}" "${APP_DIR}/.DirIcon"

# --- Desktop entry ----------------------------------------------------------
# StartupWMClass=OpenIDE coincide con product.json nameShort (Electron usa
# nameShort as WM_CLASS). If the window does not group properly in the dock, check
# con:  xprop WM_CLASS   sobre la ventana abierta.
printf '%s\n' \
	'[Desktop Entry]' \
	'Name=OpenIDE' \
	'Comment=Open source agentic development environment' \
	'GenericName=Integrated Development Environment' \
	'Exec=openide %F' \
	'Icon=openide' \
	'Type=Application' \
	'StartupNotify=true' \
	'StartupWMClass=OpenIDE' \
	'Categories=Development;IDE;TextEditor;' \
	'MimeType=text/plain;inode/directory;' \
	'Actions=new-empty-window;' \
	'' \
	'[Desktop Action new-empty-window]' \
	'Name=New Empty Window' \
	'Name[es]=Nueva ventana vacía' \
	'Exec=openide --new-window' \
	'Icon=openide' \
	> "${APP_DIR}/openide.desktop"
cp "${APP_DIR}/openide.desktop" "${APP_DIR}/usr/share/applications/openide.desktop"

# --- AppRun -----------------------------------------------------------------
printf '%s\n' \
	'#!/bin/sh' \
	'HERE="$(dirname "$(readlink -f "$0")")"' \
	'if [ "${1:-}" = "--" ]; then' \
	'\tshift' \
	'\texec "${HERE}/usr/share/openide/bin/openide" "$@"' \
	'fi' \
	'exec "${HERE}/usr/share/openide/openide" "$@"' \
	> "${APP_DIR}/AppRun"
chmod +x "${APP_DIR}/AppRun"

# --- appimagetool -----------------------------------------------------------
# The "continuous" channel is the recommended one (the numbered tags are stale).
# It is cached in ${CACHE_DIR}; for reproducibility vendor your own copy and point at it
# with APPIMAGETOOL_BIN. APPIMAGE_EXTRACT_AND_RUN=1 avoids the FUSE mount.
if [[ ! -x "${APPIMAGETOOL}" ]]; then
	echo "Bajando appimagetool (continuous) → ${APPIMAGETOOL}"
	curl --fail --location \
		'https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage' \
		--output "${APPIMAGETOOL}"
	chmod +x "${APPIMAGETOOL}"
fi

rm -f "${OUTPUT_FILE}"
ARCH="${ARCH}" APPIMAGE_EXTRACT_AND_RUN=1 "${APPIMAGETOOL}" "${APP_DIR}" "${OUTPUT_FILE}"
chmod +x "${OUTPUT_FILE}"

echo "AppImage generado: ${OUTPUT_FILE}"
