/*---------------------------------------------------------------------------------------------
 * Copyright (c) OpenIDE. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import { DESIGN_TEMPLATES, DesignDocument, DesignOperation, DesignTemplate } from '../common/openideDesign.js';
import { IOpenideCanvasService } from './openideCanvasService.js';
import { BUILTIN_CANVAS_SKILL } from './openideAgentSkills.js';
import { IAgentTool } from './openideTools.js';
export function createDesignTools(service: IOpenideCanvasService, readCapture: (path: string) => Promise<string>): IAgentTool[] {
	return [
		{ risk: 'safe', def: { name: 'canvas_templates', description: 'Discover Canvas formats. If the user has not chosen a format, offer relevant options with ask_user and wait for their choice. Structured templates include wireframes, mockups, mobile apps, slides, documents, whiteboards, animation and 3D scenes; use canvas_create for these or canvas_write for a standalone visual TSX artifact.', parameters: { type: 'object', properties: { includeTsxGuide: { type: 'boolean', description: 'Include the built-in Canvas skill, including the TSX workflow, for an external CLI.' } } } }, invoke: async (args) => JSON.stringify({ templates: DESIGN_TEMPLATES, ...(args.includeTsxGuide ? { tsxGuide: BUILTIN_CANVAS_SKILL } : {}), workflow: 'create → inspect → patch with expectedRevision → preview and test interactions → export or handoff. Native and external agents use the same documents. Mutations require IDE approval.' }) },
		{ risk: 'write', def: { name: 'canvas_create', description: 'Create a persistent interactive design from a template, open it in OpenIDE, and return its resource and revision. The user can edit screens, tokens, comments and interactions.', parameters: { type: 'object', properties: { template: { type: 'string', enum: DESIGN_TEMPLATES.map(t => t.id) }, title: { type: 'string', minLength: 1, maxLength: 200 }, device: { type: 'string', enum: ['mobile', 'tablet', 'desktop'] } }, required: ['template', 'title'] } }, approvalInfo: args => ({ title: 'Create Canvas', detail: String(args.title), path: '.openide/designs' }), invoke: async (args, _token, context) => { const created = await service.createDesign(args.template as DesignTemplate, String(args.title), args.device as DesignDocument['device']); await service.open(created.path, context?.targetWindowId); return JSON.stringify(created); } },
		{ risk: 'safe', def: { name: 'canvas_inspect', description: 'Read a structured design, its stable node IDs, interactions, tokens and current revision before editing. History is omitted to keep context small.', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } }, invoke: async (args) => { const file = await service.readDesign(String(args.path)); return JSON.stringify({ schemaVersion: file.schemaVersion, revision: file.revision, document: file.document, canUndo: !!file.past.length, canRedo: !!file.future.length }); } },
		{ risk: 'write', def: { name: 'canvas_patch', description: 'Apply an atomic batch to a structured design. Read canvas_inspect first; expectedRevision prevents overwriting concurrent user edits. Operation types: setNode, addNode, removeNode, moveNode, addScreen, duplicateScreen, removeScreen, setScreen, setToken, comment, setDocument. Nodes: id, kind (text/button/input/box/row/stack/image/shape/path/model), text, children, token, spacing (0–80), size (10–72), optional action (navigate/overlay/close/back/submit/toggle) and target screen ID. Use setAdvanced for frame (x,y,width,height,rotation), points, keyframes (time,x,y,rotation,scale,opacity), object3d (primitive,position,rotation,scale; mesh vertices/faces), or assetId. All three transform vectors require three numbers. Use canvas_import for image, OBJ and design-token files. Use operations="undo" or "redo" for history.', parameters: { type: 'object', properties: { path: { type: 'string' }, expectedRevision: { type: 'integer', minimum: 1 }, operations: { anyOf: [{ type: 'array', minItems: 1, maxItems: 100, items: { type: 'object', required: ['type'], additionalProperties: false, properties: {
											type: { type: 'string', enum: ['setNode', 'addNode', 'removeNode', 'moveNode', 'addScreen', 'duplicateScreen', 'removeScreen', 'setScreen', 'setToken', 'comment', 'setDocument', 'setAdvanced', 'setSystem', 'addAsset'] },
											id: { type: 'string', description: 'Existing node/screen ID; new screen ID for addScreen and duplicateScreen.' },
											screenId: { type: 'string', description: 'Destination screen for addNode/moveNode, source screen for duplicateScreen.' },
											parentId: { type: 'string', description: 'Optional container ID for addNode/moveNode.' }, index: { type: 'integer', minimum: 0 },
											node: { type: 'object', description: 'New node: id, kind, text, children, token, spacing, size; optional action and target.' },
											text: { type: 'string' }, token: { type: 'string' }, value: { type: 'string', description: 'Hex color for setToken.' }, spacing: { type: 'number', minimum: 0, maximum: 80 }, size: { type: 'number', minimum: 10, maximum: 72 },
											action: { type: 'string', enum: ['', 'navigate', 'overlay', 'close', 'back', 'submit', 'toggle'] }, target: { type: 'string', description: 'Destination screen ID.' },
											frame: { type: 'object' }, shape: { type: 'string', enum: ['rectangle', 'ellipse', 'line', 'arrow'] }, points: { type: 'array', items: { type: 'array', items: { type: 'number' } } }, keyframes: { type: 'array', items: { type: 'object' } }, object3d: { type: 'object' }, sourcePath: { type: 'string' }, assetId: { type: 'string' }, asset: { type: 'object' }, designSystem: { type: 'object' }, duration: { type: 'number', minimum: .1, maximum: 60 },
											device: { type: 'string', enum: ['mobile', 'tablet', 'desktop'] }, fidelity: { type: 'string', enum: ['wireframe', 'mockup'] }
										} } }, { type: 'string', enum: ['undo', 'redo'] }] } }, required: ['path', 'expectedRevision', 'operations'] } }, approvalInfo: args => ({ title: 'Edit Canvas', detail: JSON.stringify(args.operations).slice(0, 8000), path: String(args.path) }), invoke: async (args) => { const file = await service.patchDesign(String(args.path), Number(args.expectedRevision), args.operations as DesignOperation[] | 'undo' | 'redo'); return JSON.stringify({ path: args.path, revision: file.revision, document: file.document }); } },
		{ risk: 'write', def: { name: 'canvas_preview', description: 'Open a structured Canvas and capture its visible editor and prototype as an image for visual review. Writes a JPEG beside the design; this is a screenshot, not proof that its interactions work.', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } }, approvalInfo: args => ({ title: 'Capture Canvas preview', detail: String(args.path), path: String(args.path) }), invoke: async (args, _token, context) => readCapture(await service.previewDesign(String(args.path), context?.targetWindowId)) },
		{ risk: 'write', def: { name: 'canvas_import', description: 'Import a workspace image (PNG/JPEG/passive SVG), OBJ mesh or design-token JSON into the current Canvas revision. All imports are validated, bounded and undoable. Token formats: DTCG, Tokens Studio color tokens or named hex palette.', parameters: { type: 'object', properties: { path: { type: 'string' }, expectedRevision: { type: 'integer' }, sourcePath: { type: 'string' }, kind: { type: 'string', enum: ['image', 'obj', 'tokens'] }, screenId: { type: 'string' } }, required: ['path', 'expectedRevision', 'sourcePath', 'kind'] } }, approvalInfo: args => ({ title: 'Import Canvas asset', detail: String(args.sourcePath), path: String(args.path) }), invoke: async (args) => { const file = await service.importDesign(String(args.path), Number(args.expectedRevision), String(args.sourcePath), args.kind as 'image' | 'obj' | 'tokens', args.screenId as string | undefined); return JSON.stringify({ revision: file.revision, document: file.document }); } },
		{ risk: 'write', def: { name: 'canvas_export', description: 'Export the current design revision as HTML, PDF, editable PowerPoint, SVG (animated when keyframes exist), or OBJ geometry. Returns the exported file path.', parameters: { type: 'object', properties: { path: { type: 'string' }, format: { type: 'string', enum: ['html', 'pdf', 'pptx', 'svg', 'obj'] } }, required: ['path'] } }, approvalInfo: args => ({ title: 'Export Canvas', detail: String(args.path), path: String(args.path) }), invoke: async (args) => JSON.stringify(await service.exportDesign(String(args.path), args.format as 'html' | 'pdf' | 'pptx' | 'svg' | 'obj' | undefined)) },
		{ risk: 'write', def: { name: 'canvas_handoff', description: 'Write a revision-specific Markdown implementation brief containing screens, interactions, tokens, comments and acceptance criteria. Use the returned markdown in plan_save for review; a brief does not start or complete a GOAL.', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } }, approvalInfo: args => ({ title: 'Prepare Canvas handoff', detail: String(args.path), path: String(args.path) }), invoke: async (args) => JSON.stringify(await service.handoffDesign(String(args.path))) },
	];
}
