/*---------------------------------------------------------------------------------------------
 *  Copyright (c) OpenIDE. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * The Settings sections' vocabulary, in the two languages the product ships.
 *
 * These strings used to go through VS Code's `localize()` with the SPANISH text as the default.
 * `localize()` resolves against the IDE locale and only switches with a restart, and a default is
 * what you get when no language pack matches — so an English IDE rendered the whole Settings body
 * in Spanish with no way to change it. They live here instead, behind `t()`, which follows
 * `openide.language` and repaints live.
 *
 * Split out of `openideStrings.ts` only for size: 325 entries would have tripled that file. It is
 * spread into the same `STRINGS` object, so `t()` and `OpenideStringKey` see one flat dictionary.
 *
 * Terms the product brands in English in both languages (Skills, MCP, Hooks, Rules, Project Map)
 * stay put; everything with a real Spanish term is translated.
 */

export const OPENIDE_SETTINGS_STRINGS = {
	// ---- Composer commands
	'openide.commands.title': { es: 'Comandos del composer', en: 'Composer commands' },
	'openide.commands.desc': { es: 'Prompts reutilizables: tipeá /nombre en el chat y se expande el markdown del comando ($ARGUMENTS y $1..$9 interpolan lo que escribas después). Proyecto pisa global si el nombre se repite.', en: 'Reusable prompts: type /name in the chat and the command\'s markdown expands ($ARGUMENTS and $1..$9 interpolate whatever you type after it). Project overrides global when the name is repeated.' },
	'openide.commands.new': { es: 'Nuevo comando', en: 'New command' },
	'openide.commands.noProject': { es: 'No hay carpeta abierta', en: 'No folder open' },
	'openide.commands.noProjectDesc': { es: 'Abrí una carpeta, o elegí el ámbito User en la cabecera para administrar los comandos globales.', en: 'Open a folder, or pick the User scope in the header to manage global commands.' },
	'openide.commands.loading': { es: 'Cargando comandos…', en: 'Loading commands…' },
	'openide.commands.noMatch': { es: 'Ningún comando coincide', en: 'No command matches' },
	'openide.commands.tryOther': { es: 'Probá otra búsqueda.', en: 'Try another search.' },
	'openide.commands.emptyTitle': { es: 'Todavía no hay comandos', en: 'No commands yet' },
	'openide.commands.emptyDesc': { es: 'Un comando es un prompt guardado que invocás como /nombre en el chat — ideal para pedidos que repetís siempre (revisar un diff, armar un resumen, generar tests).', en: 'A command is a saved prompt you invoke as /name in the chat — ideal for requests you repeat constantly (review a diff, write a summary, generate tests).' },
	'openide.commands.global': { es: 'Global', en: 'Global' },
	'openide.commands.project': { es: 'Proyecto', en: 'Project' },
	'openide.commands.noDesc': { es: '(sin descripción)', en: '(no description)' },
	'openide.commands.open': { es: 'Abrir el .md', en: 'Open the .md' },
	'openide.commands.delete': { es: 'Eliminar el comando', en: 'Delete the command' },
	'openide.commands.loadingPreview': { es: 'Cargando preview…', en: 'Loading preview…' },
	'openide.commands.emptyBody': { es: '(vacío)', en: '(empty)' },
	'openide.commands.previewBody': { es: 'Cuerpo (lo que ve el modelo):', en: 'Body (what the model sees):' },
	'openide.commands.previewExample': { es: 'Ejemplo con args: /{0} ejemplo "dos palabras"', en: 'Example with args: /{0} example "two words"' },
	'openide.commands.deleteConfirm': { es: '¿Eliminar el comando /{0}?', en: 'Delete the command /{0}?' },
	'openide.commands.deleteButton': { es: 'Eliminar', en: 'Delete' },
	'openide.commands.noProjectToast': { es: 'No hay carpeta abierta: elegí el ámbito User en la cabecera.', en: 'No folder open: pick the User scope in the header.' },
	'openide.commands.newPrompt': { es: 'Nombre del comando (se invoca como /nombre en el chat)', en: 'Command name (invoked as /name in the chat)' },
	'openide.commands.newPlaceholder': { es: 'ej: revisar-diff, resumen-standup', en: 'e.g. review-diff, standup-summary' },
	'openide.commands.nameInvalid': { es: 'kebab-case: a-z, 0-9 y guiones; sin -- ni guiones en los bordes.', en: 'kebab-case: a-z, 0-9 and hyphens; no -- and no hyphens at the edges.' },
	'openide.commands.exists': { es: 'Ya existe /{0} en este ámbito.', en: '/{0} already exists in this scope.' },
	// ---- Shell hooks
	'openide.hooks.preToolUse': { es: 'Antes de cada tool: puede BLOQUEAR la llamada (decision: block).', en: 'Before each tool: can BLOCK the call (decision: block).' },
	'openide.hooks.postToolUse': { es: 'Después de cada tool: observa el resultado (no bloquea).', en: 'After each tool: observes the result (does not block).' },
	'openide.hooks.userPromptSubmit': { es: 'Al enviar un mensaje: puede inyectar contexto ({"context": "…"}).', en: 'On sending a message: can inject context ({"context": "…"}).' },
	'openide.hooks.sessionStart': { es: 'Al arrancar una conversación (observador).', en: 'When a conversation starts (observer).' },
	'openide.hooks.stop': { es: 'Al terminar un turno del agente (observador).', en: 'When an agent turn ends (observer).' },
	'openide.hooks.subagentStop': { es: 'Al terminar un subagente (observador).', en: 'When a subagent finishes (observer).' },
	'openide.hooks.title': { es: 'Hooks de shell', en: 'Shell hooks' },
	'openide.hooks.desc': { es: 'Tus scripts enganchados al lifecycle del agente: bloquear tools peligrosas, formatear después de escribir, inyectar contexto al enviar. Cada hook pide tu consentimiento la primera vez, y otra vez si el script cambió.', en: 'Your scripts hooked into the agent\'s lifecycle: block dangerous tools, format after writing, inject context on send. Each hook asks for your consent the first time, and again if the script changes.' },
	'openide.hooks.editJson': { es: 'Editar hooks.json', en: 'Edit hooks.json' },
	'openide.hooks.new': { es: 'Nuevo hook', en: 'New hook' },
	'openide.hooks.loading': { es: 'Cargando hooks…', en: 'Loading hooks…' },
	'openide.hooks.emptyTitle': { es: 'Sin hooks configurados', en: 'No hooks configured' },
	'openide.hooks.emptyDesc': { es: 'Un hook corre un script tuyo en momentos clave: antes de cada tool (puede bloquearla), después (formatear/lint), o al enviar un mensaje (inyectar contexto). El asistente te guía paso a paso.', en: 'A hook runs a script of yours at key moments: before each tool (it can block it), after (format/lint), or when you send a message (inject context). The assistant walks you through it.' },
	'openide.hooks.noMatch': { es: 'Ningún hook coincide con la búsqueda.', en: 'No hook matches the search.' },
	'openide.hooks.orphans': { es: 'Aprobaciones huérfanas', en: 'Orphaned approvals' },
	'openide.hooks.orphansDesc': { es: 'Hooks aprobados que ya no están en ningún hooks.json — revocalos si no los vas a volver a usar.', en: 'Approved hooks no longer present in any hooks.json — revoke them if you are not going to use them again.' },
	'openide.hooks.revoke': { es: 'Revocar la aprobación', en: 'Revoke the approval' },
	'openide.hooks.global': { es: 'Global', en: 'Global' },
	'openide.hooks.project': { es: 'Proyecto', en: 'Project' },
	'openide.hooks.approved': { es: 'Aprobado', en: 'Approved' },
	'openide.hooks.drifted': { es: 'Modificado desde aprobación', en: 'Modified since approval' },
	'openide.hooks.pending': { es: 'Pendiente', en: 'Pending' },
	'openide.hooks.reapprove': { es: 'Re-aprobar', en: 'Re-approve' },
	'openide.hooks.approve': { es: 'Aprobar', en: 'Approve' },
	'openide.hooks.timeout': { es: 'timeout {0}s', en: 'timeout {0}s' },
	'openide.hooks.test': { es: 'Probar con un payload sintético', en: 'Test with a synthetic payload' },
	'openide.hooks.running': { es: 'Corriendo el hook con un payload sintético de {0}…', en: 'Running the hook with a synthetic {0} payload…' },
	'openide.hooks.testFailed': { es: 'El hook no pudo ejecutarse:', en: 'The hook could not run:' },
	'openide.hooks.exit': { es: 'exit {0}', en: 'exit {0}' },
	'openide.hooks.block': { es: 'BLOCK: {0}', en: 'BLOCK: {0}' },
	'openide.hooks.context': { es: 'context inyectado ({0} chars)', en: 'context injected ({0} chars)' },
	'openide.hooks.noStdout': { es: '(sin stdout)', en: '(no stdout)' },
	'openide.hooks.noProject': { es: 'No hay carpeta abierta: elegí el ámbito User en la cabecera.', en: 'No folder open: pick the User scope in the header.' },
	'openide.hooks.pickEvent': { es: '¿Qué evento del agente dispara el hook?', en: 'Which agent event fires the hook?' },
	'openide.hooks.promptCommand': { es: 'Comando a ejecutar (recibe el payload JSON por stdin; ~ y rutas relativas al workspace valen)', en: 'Command to run (receives the JSON payload on stdin; ~ and workspace-relative paths are fine)' },
	'openide.hooks.commandRequired': { es: 'Falta el comando.', en: 'The command is missing.' },
	'openide.hooks.promptMatcher': { es: 'Filtro de tools (regex, opcional — Enter vacío = todas)', en: 'Tool filter (regex, optional — empty Enter = all)' },
	'openide.hooks.approveNow': { es: '¿Aprobar ya el hook "{0}"?', en: 'Approve the hook "{0}" now?' },
	'openide.hooks.approveDetail': { es: 'Los hooks corren con tus credenciales completas. Si el script cambia después, se vuelve a preguntar. Podés aprobarlo más tarde desde la lista.', en: 'Hooks run with your full credentials. If the script changes later, you will be asked again. You can approve it later from the list.' },
	'openide.hooks.later': { es: 'Después', en: 'Later' },
	// ---- MCP servers
	'openide.mcp.noProject': { es: 'No hay carpeta abierta: usá el ámbito User.', en: 'No folder open: use the User scope.' },
	'openide.mcp.title': { es: 'Servidores MCP', en: 'MCP servers' },
	'settings.import.title': { es: 'Importar configuración', en: 'Import settings' },
	'settings.import.none': { es: 'No hay nada para importar', en: 'Nothing to import' },
	'settings.import.noneDesc': { es: 'No se encontró VS Code, VSCodium, Cursor ni Windsurf, ni Claude Code, Codex, opencode o Gemini CLI con configuración en este equipo.', en: 'No VS Code, VSCodium, Cursor or Windsurf, and no Claude Code, Codex, opencode or Gemini CLI with a configuration, was found on this machine.' },
	'settings.import.desc': { es: 'Trae lo que ya tenés en otro editor o en un CLI de agentes: settings, atajos, snippets y extensiones de VS Code, Cursor o Windsurf; servers MCP y reglas globales de Claude Code, Codex, opencode o Gemini CLI. Lo que ya está configurado acá no se pisa.', en: 'Bring over what you already have in another editor or an agent CLI: settings, keybindings, snippets and extensions from VS Code, Cursor or Windsurf; MCP servers and global rules from Claude Code, Codex, opencode or Gemini CLI. What is already configured here is never overwritten.' },
	'settings.import.ides': { es: 'Editores', en: 'Editors' },
	'settings.import.clis': { es: 'CLIs de agentes', en: 'Agent CLIs' },
	'settings.import.scanning': { es: 'buscando', en: 'looking' },
	'settings.import.found': { es: 'configuración', en: 'config found' },
	'settings.import.installed': { es: 'instalado', en: 'installed' },
	'settings.import.installedNothing': { es: 'Instalado en {0}; todavía no tiene nada para importar.', en: 'Installed at {0}; nothing to import from it yet.' },
	'settings.import.missing': { es: 'no encontrado', en: 'not found' },
	'settings.import.settings': { es: 'Settings', en: 'Settings' },
	'settings.import.keybindings': { es: 'Atajos', en: 'Keybindings' },
	'settings.import.snippets': { es: 'Snippets', en: 'Snippets' },
	'settings.import.extensions': { es: 'Extensiones', en: 'Extensions' },
	'settings.import.mcp': { es: 'Servers MCP', en: 'MCP servers' },
	'settings.import.rules': { es: 'Reglas', en: 'Rules' },
	'settings.import.itemCount': { es: '{0} ({1})', en: '{0} ({1})' },
	'settings.import.nothing': { es: 'No se encontró nada para importar de {0}.', en: 'Nothing to import from {0}.' },
	'settings.import.importSettings': { es: 'Importar {0} settings', en: 'Import {0} settings' },
	'settings.import.importKeybindings': { es: 'Importar {0} atajos', en: 'Import {0} keybindings' },
	'settings.import.importSnippets': { es: 'Importar {0} snippets', en: 'Import {0} snippets' },
	'settings.import.installExtensions': { es: 'Instalar {0} extensiones', en: 'Install {0} extensions' },
	'settings.import.importMcp': { es: 'Importar {0} servers MCP', en: 'Import {0} MCP servers' },
	'settings.import.importRules': { es: 'Importar reglas como regla global', en: 'Import rules as a global rule' },
	'settings.import.doneSettings': { es: '{0} settings importados de {1}.', en: '{0} settings imported from {1}.' },
	'settings.import.doneKeybindings': { es: '{0} atajos agregados de {1}; {2} ya existían.', en: '{0} keybindings added from {1}; {2} already existed.' },
	'settings.import.doneSnippets': { es: '{0} snippets copiados de {1}.', en: '{0} snippets copied from {1}.' },
	'settings.import.doneExtensions': { es: '{0} extensiones instaladas de {1}; {2} no se pudieron instalar.', en: '{0} extensions installed from {1}; {2} could not be installed.' },
	'settings.import.doneMcp': { es: '{0} servers MCP agregados de {1}; {2} ya existían con ese nombre.', en: '{0} MCP servers added from {1}; {2} already existed under that name.' },
	'settings.import.doneRules': { es: 'Reglas de {0} guardadas como la regla global «{1}».', en: '{0} rules saved as the global rule "{1}".' },
	'settings.import.failed': { es: 'La importación desde {0} falló: {1}', en: 'Importing from {0} failed: {1}' },
	'settings.import.extensionsNote': { es: 'Las extensiones se instalan desde el marketplace de OpenIDE; las que sólo existen en el de Microsoft no van a estar.', en: 'Extensions install from OpenIDE\'s marketplace; the ones that only exist in Microsoft\'s will not be found.' },
	'openide.mcp.desc': { es: 'Herramientas externas que el agente puede usar. Se configuran en mcp.json y se conectan al guardar.', en: 'External tools the agent can use. They are configured in mcp.json and connect on save.' },
	'openide.mcp.add': { es: 'Agregar server', en: 'Add server' },
	'openide.mcp.reload': { es: 'Recargar', en: 'Reload' },
	'openide.mcp.enabledName': { es: 'MCP habilitado', en: 'MCP enabled' },
	'openide.mcp.enabledDesc': { es: 'Con esto apagado el agente no conecta ningún server ni ve sus herramientas.', en: 'With this off the agent connects to no server and sees none of their tools.' },
	'openide.mcp.noProjectTitle': { es: 'No hay carpeta abierta', en: 'No folder open' },
	'openide.mcp.noProjectDesc': { es: 'Abrí una carpeta, o elegí el ámbito User en la cabecera para administrar los servers globales.', en: 'Open a folder, or pick the User scope in the header to manage global servers.' },
	'openide.mcp.metricServers': { es: 'servers', en: 'servers' },
	'openide.mcp.metricConnected': { es: 'conectados', en: 'connected' },
	'openide.mcp.metricTools': { es: 'herramientas', en: 'tools' },
	'openide.mcp.emptyTitle': { es: 'Todavía no hay servers en este ámbito', en: 'No servers in this scope yet' },
	'openide.mcp.emptyDesc': { es: 'Pegá el bloque "mcpServers" del README de cualquier server, configurá uno a mano, o instalá uno de los populares.', en: 'Paste the "mcpServers" block from any server\'s README, configure one by hand, or install one of the popular ones.' },
	'openide.mcp.stOff': { es: 'MCP apagado', en: 'MCP off' },
	'openide.mcp.stDisabled': { es: 'deshabilitado', en: 'disabled' },
	'openide.mcp.stInvalid': { es: 'config inválida', en: 'invalid config' },
	'openide.mcp.stConnected': { es: 'conectado · {0} tools', en: 'connected · {0} tools' },
	'openide.mcp.stConnecting': { es: 'conectando…', en: 'connecting…' },
	'openide.mcp.stParkedTip': { es: 'Sin reconexión automática: "Recargar" lo reintenta.', en: 'No automatic reconnection: "Reload" retries it.' },
	'openide.mcp.stRetryTip': { es: 'Reintentando reconectar…', en: 'Retrying the connection…' },
	'openide.mcp.stParked': { es: 'parkeado', en: 'parked' },
	'openide.mcp.stError': { es: 'error', en: 'error' },
	'openide.mcp.stIdle': { es: 'sin conectar', en: 'not connected' },
	'openide.mcp.shadowed': { es: 'sobreescrito por el proyecto', en: 'overridden by the project' },
	'openide.mcp.noSummary': { es: '(sin command ni url)', en: '(no command or url)' },
	'openide.mcp.toggleTip': { es: 'Conectar este server', en: 'Connect this server' },
	'openide.mcp.errName': { es: 'Nombre inválido: letras, números, guiones y _; tiene que empezar alfanumérico.', en: 'Invalid name: letters, numbers, hyphens and _; it has to start alphanumeric.' },
	'openide.mcp.errJson': { es: 'El JSON avanzado no parsea.', en: 'The advanced JSON does not parse.' },
	'openide.mcp.errCommand': { es: 'Falta el command (stdio).', en: 'The command is missing (stdio).' },
	'openide.mcp.errUrl': { es: 'La URL tiene que ser http(s).', en: 'The URL has to be http(s).' },
	'openide.mcp.fieldName': { es: 'Nombre', en: 'Name' },
	'openide.mcp.fieldTransport': { es: 'Transporte', en: 'Transport' },
	'openide.mcp.fieldArgs': { es: 'Args (uno por línea)', en: 'Args (one per line)' },
	'openide.mcp.envDesc': { es: 'Los valores guardados nunca se muestran.', en: 'Saved values are never shown.' },
	'openide.mcp.addEnv': { es: 'Agregar variable', en: 'Add variable' },
	'openide.mcp.headersDesc': { es: 'Los valores guardados nunca se muestran.', en: 'Saved values are never shown.' },
	'openide.mcp.addHeader': { es: 'Agregar header', en: 'Add header' },
	'openide.mcp.advanced': { es: 'JSON avanzado (timeout, tools.include/exclude…)', en: 'Advanced JSON (timeout, tools.include/exclude…)' },
	'openide.mcp.advancedLabel': { es: 'Entrada JSON', en: 'JSON input' },
	'openide.mcp.advancedDesc': { es: 'Si editás acá, al guardar se manda este JSON. Los valores {0} conservan el secreto guardado.', en: 'If you edit here, this JSON is what gets sent on save. {0} values keep the stored secret.' },
	'openide.mcp.testing': { es: 'Probando…', en: 'Testing…' },
	'openide.mcp.test': { es: 'Probar', en: 'Test' },
	'openide.mcp.save': { es: 'Guardar', en: 'Save' },
	'openide.mcp.openJson': { es: 'Abrir mcp.json', en: 'Open mcp.json' },
	'openide.mcp.remove': { es: 'Quitar', en: 'Remove' },
	'openide.mcp.removeConfirm': { es: 'Confirmar: quitar el server', en: 'Confirm: remove the server' },
	'openide.mcp.filesTitle': { es: 'Archivos de configuración', en: 'Configuration files' },
	'openide.mcp.filesDesc': { es: 'De dónde salen los servers. Un archivo que no parsea deja de aportar servers sin más aviso que este.', en: 'Where the servers come from. A file that does not parse stops contributing servers with no warning other than this one.' },
	'openide.mcp.fileInvalid': { es: 'no parsea', en: 'does not parse' },
	'openide.mcp.fileMissing': { es: 'no existe', en: 'does not exist' },
	'openide.mcp.fileServers': { es: '{0} servers', en: '{0} servers' },
	'openide.mcp.fileProject': { es: 'Sólo este workspace. Sus servers ganan sobre los globales con el mismo nombre.', en: 'This workspace only. Its servers win over global ones with the same name.' },
	'openide.mcp.fileGlobal': { es: 'Disponible en todos tus proyectos.', en: 'Available across all your projects.' },
	'openide.mcp.fileOpen': { es: 'Abrir', en: 'Open' },
	'openide.mcp.fileCreate': { es: 'Crear', en: 'Create' },
	'openide.mcp.saved': { es: 'Server "{0}" guardado. Reconectando…', en: 'Server "{0}" saved. Reconnecting…' },
	'openide.mcp.testOk': { es: '✓ {0} tool(s){1}', en: '✓ {0} tool(s){1}' },
	'openide.mcp.scopeUser': { es: 'Usuario', en: 'User' },
	'openide.mcp.scopeUserDesc': { es: 'Disponible en todos tus proyectos', en: 'Available across all your projects' },
	'openide.mcp.scopeProject': { es: 'Proyecto', en: 'Project' },
	'openide.mcp.scopeProjectDesc': { es: 'Sólo este workspace (.openide/)', en: 'This workspace only (.openide/)' },
	'openide.mcp.namePrompt': { es: 'Nombre del server (su identificador en mcp.json)', en: 'Server name (its identifier in mcp.json)' },
	'openide.mcp.scopeAsk': { es: '¿Dónde guardar el server "{0}"?', en: 'Where should the server "{0}" be saved?' },
	'openide.mcp.added': { es: 'Server "{0}" agregado. Conectando…', en: 'Server "{0}" added. Connecting…' },
	'openide.mcp.promptRequired': { es: 'Este dato es obligatorio para {0}.', en: 'This value is required for {0}.' },
	'openide.mcp.pastePrompt': { es: 'Pegá el JSON del server (el bloque "mcpServers" del README — formato Claude Code, Cursor o VS Code)', en: 'Paste the server JSON (the "mcpServers" block from the README — Claude Code, Cursor or VS Code format)' },
	'openide.mcp.pastePick': { es: 'Se encontraron {0} servers — elegí cuáles importar', en: '{0} servers found — pick which ones to import' },
	'openide.mcp.pasteScope': { es: '¿Dónde guardar los servers importados?', en: 'Where should the imported servers be saved?' },
	'openide.mcp.pasteSaved': { es: '{0} server(s) importados: {1}. Conectando…', en: '{0} server(s) imported: {1}. Connecting…' },
	'openide.mcp.sepManual': { es: 'Configurar a mano', en: 'Configure by hand' },
	'openide.mcp.addJson': { es: 'Pegar JSON', en: 'Paste JSON' },
	'openide.mcp.addJsonDetail': { es: 'El bloque "mcpServers" del README de cualquier server (Claude Code / Cursor / VS Code)', en: 'The "mcpServers" block from any server\'s README (Claude Code / Cursor / VS Code)' },
	'openide.mcp.addStdio': { es: 'Comando local (stdio)', en: 'Local command (stdio)' },
	'openide.mcp.addStdioDetail': { es: 'Cualquier proceso local que implemente MCP (npx, node, python, docker…)', en: 'Any local process implementing MCP (npx, node, python, docker…)' },
	'openide.mcp.addHttp': { es: 'Server remoto (HTTP)', en: 'Remote server (HTTP)' },
	'openide.mcp.addHttpDetail': { es: 'Una URL http(s) que implemente MCP (Streamable HTTP)', en: 'An http(s) URL implementing MCP (Streamable HTTP)' },
	'openide.mcp.sepCatalog': { es: 'Populares', en: 'Popular' },
	'openide.mcp.addPlaceholder': { es: 'Agregar server MCP: pegá su JSON, configuralo a mano o instalá uno popular', en: 'Add MCP server: paste its JSON, configure it by hand or install a popular one' },
	'openide.mcp.stdioPrompt': { es: 'Comando a ejecutar, con sus argumentos', en: 'Command to run, with its arguments' },
	'openide.mcp.stdioRequired': { es: 'Falta el comando.', en: 'The command is missing.' },
	'openide.mcp.httpPrompt': { es: 'URL del server MCP', en: 'MCP server URL' },
	'openide.mcp.httpInvalid': { es: 'Tiene que ser una URL http(s).', en: 'It has to be an http(s) URL.' },
	'openide.mcp.httpAuthPrompt': { es: 'Header Authorization (opcional — Enter vacío para saltear)', en: 'Authorization header (optional — empty Enter to skip)' },
	// ---- AI providers
	'openide.providers.paintError': { es: 'No se pudo cargar Proveedores', en: 'Could not load Providers' },
	'openide.providers.retry': { es: 'Reintentar', en: 'Retry' },
	'openide.providers.title': { es: 'Proveedores', en: 'Providers' },
	// ---- fallback chain: where a turn goes when the chosen model will not answer.
	'openide.chain.title': { es: 'Cadena de respaldo', en: 'Fallback chain' },
	'openide.chain.desc': { es: 'A dónde pasa OpenIDE cuando el modelo elegido falla por límite de ritmo, cuota o red — en este orden, y sólo antes de que la respuesta haya empezado. Un modelo que falla queda en enfriamiento, así los turnos siguientes arrancan directo en el siguiente paso.', en: 'Where OpenIDE moves when the chosen model fails on a rate limit, quota or the network — in this order, and only before an answer has started. A model that fails is put on cooldown, so later turns start on the next step directly.' },
	'openide.chain.empty': { es: 'Sin cadena: cuando el modelo elegido falla, el turno termina en un aviso.', en: 'No chain: when the chosen model fails, the turn ends in a notice.' },
	'openide.chain.add': { es: 'Agregar modelo…', en: 'Add a model…' },
	'openide.chain.pick': { es: 'Elegí el modelo al que caer', en: 'Pick the model to fall back to' },
	'openide.chain.up': { es: 'Subir', en: 'Move up' },
	'openide.chain.down': { es: 'Bajar', en: 'Move down' },
	'openide.chain.remove': { es: 'Quitar de la cadena', en: 'Remove from the chain' },
	'openide.chain.step': { es: '{0}. {1}', en: '{0}. {1}' },
	'openide.chain.cooling': { es: 'en enfriamiento, vuelve en {0}', en: 'cooling down, back in {0}' },
	'openide.chain.gone': { es: 'proveedor no conectado', en: 'provider not connected' },
	'openide.chain.already': { es: 'Ese modelo ya está en la cadena.', en: 'That model is already in the chain.' },
	'openide.providers.desc': { es: 'Conectá tu cuenta o pegá una API key. Las credenciales se guardan cifradas en el almacén de secretos del sistema — nunca en settings.json.', en: 'Connect your account or paste an API key. Credentials are stored encrypted in the system secret store — never in settings.json.' },
	'openide.providers.filter': { es: 'Buscar proveedor…', en: 'Search providers…' },
	'openide.providers.filterClear': { es: 'Limpiar la búsqueda', en: 'Clear the search' },
	'openide.providers.filterCount': { es: '{0} de {1}', en: '{0} of {1}' },
	'openide.providers.noMatch': { es: 'Ningún proveedor coincide con «{0}»', en: 'No provider matches “{0}”' },
	'openide.providers.noMatchText': { es: 'Probá con el nombre del proveedor, la empresa o el tipo de credencial (OAuth, API key).', en: 'Try the provider name, the company, or the kind of credential (OAuth, API key).' },
	'openide.providers.groupConnected': { es: 'Conectados', en: 'Connected' },
	'openide.providers.groupAvailable': { es: 'Disponibles', en: 'Available' },
	'openide.providers.groupAll': { es: 'Todos los proveedores', en: 'All providers' },
	'openide.providers.noActive': { es: 'Sin proveedor activo', en: 'No active provider' },
	'openide.providers.noActiveText': { es: 'Conectá uno de la lista para poder usar el chat.', en: 'Connect one from the list to be able to use the chat.' },
	'openide.providers.rowActiveModel': { es: 'Activo · {0}', en: 'Active · {0}' },
	'openide.providers.rowActive': { es: 'Activo', en: 'Active' },
	'openide.providers.rowConnected': { es: 'Conectado', en: 'Connected' },
	'openide.providers.authOAuth': { es: 'Cuenta / suscripción', en: 'Account / subscription' },
	'openide.providers.authKey': { es: 'API key', en: 'API key' },
	'openide.providers.authNone': { es: 'Local, sin credenciales', en: 'Local, no credentials' },
	'openide.providers.addCustom': { es: 'Proveedor personalizado', en: 'Custom provider' },
	'openide.providers.addCustomSub': { es: 'Cualquier endpoint OpenAI-compatible o Anthropic, vía openide.agent.customProviders', en: 'Any OpenAI-compatible or Anthropic endpoint, via openide.agent.customProviders' },
	'openide.providers.gone': { es: 'Este proveedor ya no existe', en: 'This provider no longer exists' },
	'openide.providers.goneDesc': { es: 'Se quitó del catálogo o de tus proveedores personalizados.', en: 'It was removed from the catalogue or from your custom providers.' },
	'openide.providers.back': { es: 'Volver a Proveedores', en: 'Back to Providers' },
	'openide.providers.use': { es: 'Usar este proveedor', en: 'Use this provider' },
	'openide.providers.secAuth': { es: 'Autenticación', en: 'Authentication' },
	'openide.providers.getKey': { es: 'Conseguir una API key', en: 'Get an API key' },
	'openide.providers.secUsage': { es: 'Uso del plan', en: 'Plan usage' },
	'openide.providers.secAccounts': { es: 'Cuentas', en: 'Accounts' },
	'openide.providers.secSession': { es: 'Sesión', en: 'Session' },
	'openide.providers.reconnect': { es: 'Reconectar', en: 'Reconnect' },
	'openide.providers.signOut': { es: 'Cerrar sesión', en: 'Sign out' },
	'openide.providers.signOutConfirm': { es: 'Confirmar: cerrar sesión', en: 'Confirm: sign out' },
	'openide.providers.clearKey': { es: 'Borrar API key', en: 'Delete API key' },
	'openide.providers.clearKeyConfirm': { es: 'Confirmar: borrar la key', en: 'Confirm: delete the key' },
	'openide.providers.secConnect': { es: 'Conectar', en: 'Connect' },
	'openide.providers.connectWith': { es: 'Conectar con {0}', en: 'Connect with {0}' },
	'openide.providers.noAuthOffline': { es: 'Servidor local sin responder. No necesita credenciales: alcanza con que esté corriendo y volver a entrar acá.', en: 'Local server not responding. It needs no credentials: it just has to be running — then come back here.' },
	'openide.providers.secModels': { es: 'Modelos', en: 'Models' },
	'openide.providers.modelsPreview': { es: 'El catálogo del proveedor. Conectá para usarlos.', en: 'The provider\'s catalogue. Connect to use them.' },
	'openide.providers.modelSearch': { es: 'Buscar modelos', en: 'Search models' },
	'openide.providers.modelNoResults': { es: 'Sin resultados para "{0}".', en: 'No results for "{0}".' },
	'openide.providers.modelDraftHint': { es: 'Se aplica al tocar "Usar este proveedor".', en: 'Applied when you press "Use this provider".' },
	'openide.providers.modelOther': { es: 'Escribir otro modelo…', en: 'Type another model…' },
	'openide.providers.modelDefaultBadge': { es: 'default', en: 'default' },
	'openide.providers.modelContext': { es: '{0} ctx', en: '{0} ctx' },
	'openide.providers.secretsTitle': { es: 'Las credenciales no se están guardando en disco', en: 'Credentials are not being saved to disk' },
	'openide.providers.secretsText': { es: 'En este entorno no hay un keyring del sistema (típico en Linux sin GNOME/KDE). Las API keys y sesiones OAuth viven sólo en memoria y se pierden al reiniciar.', en: 'There is no system keyring in this environment (typical on Linux without GNOME/KDE). API keys and OAuth sessions live only in memory and are lost on restart.' },
	'openide.providers.secretsFix': { es: 'Activá el almacenamiento local, reiniciá, y volvé a conectar tus proveedores una vez.', en: 'Turn on local storage, restart, and connect your providers once more.' },
	'openide.providers.enabling': { es: 'Activando…', en: 'Turning on…' },
	'openide.providers.enableStore': { es: 'Guardar en disco y reiniciar', en: 'Save to disk and restart' },
	'openide.providers.stActive': { es: 'activo', en: 'active' },
	'openide.providers.stConnected': { es: 'conectado', en: 'connected' },
	'openide.providers.stNoAuth': { es: 'sin credenciales', en: 'no credentials' },
	'openide.providers.stDisconnected': { es: 'sin conectar', en: 'not connected' },
	'openide.providers.keyReplace': { es: 'Hay una key guardada — pegá una nueva para reemplazarla', en: 'There is a key stored — paste a new one to replace it' },
	'openide.providers.keyPaste': { es: 'Pegá tu API key de {0}', en: 'Paste your {0} API key' },
	'openide.providers.saving': { es: 'Guardando…', en: 'Saving…' },
	'openide.providers.connecting': { es: 'Conectando…', en: 'Connecting…' },
	'openide.providers.saveKey': { es: 'Guardar key', en: 'Save key' },
	'openide.providers.connectKey': { es: 'Conectar', en: 'Connect' },
	'openide.providers.keyConnected': { es: '{0} conectado.', en: '{0} connected.' },
	'openide.providers.keySavedNoAnswer': { es: 'La key se guardó, pero {0} todavía no responde. Revisá la key o reintentá en un momento.', en: 'The key was saved, but {0} is not answering yet. Check the key or retry in a moment.' },
	'openide.providers.accountsEmpty': { es: 'Sin cuentas guardadas todavía — se registra sola la primera vez que conectás.', en: 'No accounts stored yet — one registers itself the first time you connect.' },
	'openide.providers.accountReauth': { es: 'Reautenticar esta cuenta', en: 'Re-authenticate this account' },
	'openide.providers.accountRemove': { es: 'Quitar cuenta', en: 'Remove account' },
	'openide.providers.accountAdd': { es: 'Agregar cuenta', en: 'Add account' },
	'openide.providers.newAccountKey': { es: 'API key de la cuenta nueva', en: 'API key for the new account' },
	'openide.providers.reauthKey': { es: 'Nueva API key para "{0}"', en: 'New API key for "{0}"' },
	'openide.providers.customModelPrompt': { es: 'Nombre exacto del modelo, como lo espera la API de {0}', en: 'Exact model name, as the {0} API expects it' },
	'openide.providers.usageLoading': { es: 'Consultando…', en: 'Checking…' },
	'openide.providers.usageRefresh': { es: 'Actualizar', en: 'Refresh' },
	'openide.providers.usageWait': { es: 'Consultando límites…', en: 'Checking limits…' },
	'openide.providers.usageNone': { es: 'El proveedor no reportó ventanas de rate-limit.', en: 'The provider reported no rate-limit windows.' },
	'openide.providers.usageWindow': { es: 'Uso', en: 'Usage' },
	'openide.providers.resetMinutes': { es: 'se renueva en {0} min', en: 'renews in {0} min' },
	'openide.providers.resetHours': { es: 'se renueva en {0} h', en: 'renews in {0} h' },
	'openide.providers.resetDays': { es: 'se renueva en {0} días', en: 'renews in {0} days' },
	'openide.providers.oauthStart': { es: 'Conectando con {0}…', en: 'Connecting with {0}…' },
	'openide.providers.oauthStartText': { es: 'Se está abriendo tu navegador para autorizar el acceso.', en: 'Your browser is opening so you can authorise access.' },
	'openide.providers.cancel': { es: 'Cancelar', en: 'Cancel' },
	'openide.providers.oauthCode': { es: 'Ingresá este código en tu navegador', en: 'Enter this code in your browser' },
	'openide.providers.oauthCodeText': { es: 'Abrimos la página de autorización. Si no se abrió, entrá manualmente e ingresá el código:', en: 'We opened the authorisation page. If it did not open, go there manually and enter the code:' },
	'openide.providers.copy': { es: 'Copiar', en: 'Copy' },
	'openide.providers.reopen': { es: 'Abrir de nuevo', en: 'Open again' },
	'openide.providers.oauthWaiting': { es: 'Esperando autorización…', en: 'Waiting for authorisation…' },
	'openide.providers.oauthPaste': { es: 'Pegá el código de autorización', en: 'Paste the authorisation code' },
	'openide.providers.oauthPasteText': { es: 'Autorizá en el navegador y pegá acá el código (o la URL completa de redirección).', en: 'Authorise in the browser and paste the code here (or the full redirect URL).' },
	'openide.providers.oauthCodeLabel': { es: 'Código', en: 'Code' },
	'openide.providers.oauthCodePlaceholder': { es: 'código o URL de callback', en: 'code or callback URL' },
	'openide.providers.continue': { es: 'Continuar', en: 'Continue' },
	'openide.providers.oauthError': { es: 'No se pudo conectar {0}', en: 'Could not connect {0}' },
	'openide.providers.oauthErrorUnknown': { es: 'Error desconocido.', en: 'Unknown error.' },
	'openide.providers.openSettings': { es: 'Abrir configuración', en: 'Open settings' },
	'openide.providers.oauthCancelled': { es: 'Inicio de sesión cancelado o código expirado.', en: 'Sign-in cancelled or code expired.' },
	'openide.providers.rowConnect': { es: 'Conectar', en: 'Connect' },
	'openide.providers.backShort': { es: 'Volver', en: 'Back' },
	'openide.providers.signIn': { es: 'Iniciar sesión', en: 'Sign in' },
	'openide.providers.accountMenu': { es: 'Más acciones', en: 'More actions' },
	'openide.providers.retryProbe': { es: 'Volver a comprobar', en: 'Check again' },
	'openide.providers.keyStored': { es: 'Guardada en el almacén de secretos', en: 'Stored in the secret store' },
	'openide.providers.accountDefault': { es: 'Predeterminada', en: 'Default' },
	'openide.providers.accountSetDefault': { es: 'Usar como predeterminada', en: 'Set default' },
	'openide.providers.activeDisconnected': { es: '{0} es el proveedor activo pero no está conectado', en: '{0} is the active provider but it is not connected' },
	'openide.providers.activeDisconnectedText': { es: 'El chat va a fallar hasta que lo vuelvas a conectar o hagas activo otro proveedor conectado.', en: 'The chat will fail until you reconnect it or make another connected provider the active one.' },
	'openide.providers.modelsSummary': { es: '{0} modelos', en: '{0} models' },
	// ---- Terminal quick commands
	'openide.quickCommands.title': { es: 'Comandos rápidos de terminal', en: 'Terminal quick commands' },
	'openide.quickCommands.desc': { es: 'Atajos con nombre para comandos que repetís en la terminal. Aparecen en la terminal del agente para ejecutarlos de un click.', en: 'Named shortcuts for commands you repeat in the terminal. They show up in the agent\'s terminal so you can run them in one click.' },
	'openide.quickCommands.new': { es: 'Nuevo comando rápido', en: 'New quick command' },
	'openide.quickCommands.noProject': { es: 'No hay carpeta abierta', en: 'No folder open' },
	'openide.quickCommands.noProjectDesc': { es: 'Abrí una carpeta, o elegí el ámbito User en la cabecera para administrar los comandos globales.', en: 'Open a folder, or pick the User scope in the header to manage global commands.' },
	'openide.quickCommands.loading': { es: 'Cargando comandos…', en: 'Loading commands…' },
	'openide.quickCommands.noMatch': { es: 'Ningún comando coincide', en: 'No command matches' },
	'openide.quickCommands.emptyTitle': { es: 'Todavía no hay comandos rápidos', en: 'No quick commands yet' },
	'openide.quickCommands.emptyDesc': { es: 'Guardá los comandos que más repetís (levantar el dev server, correr los tests, limpiar el build) para lanzarlos sin volver a tipearlos.', en: 'Save the commands you repeat the most (start the dev server, run the tests, clean the build) so you can launch them without typing them again.' },
	'openide.quickCommands.edit': { es: 'Editar', en: 'Edit' },
	'openide.quickCommands.delete': { es: 'Eliminar', en: 'Delete' },
	'openide.quickCommands.label': { es: 'Nombre', en: 'Name' },
	'openide.quickCommands.labelPlaceholder': { es: 'ej: Dev server', en: 'e.g. Dev server' },
	'openide.quickCommands.command': { es: 'Comando', en: 'Command' },
	'openide.quickCommands.save': { es: 'Guardar', en: 'Save' },
	'openide.quickCommands.cancel': { es: 'Cancelar', en: 'Cancel' },
	'openide.quickCommands.incomplete': { es: 'Hacen falta el nombre y el comando.', en: 'Both the name and the command are required.' },
	'openide.quickCommands.deleteConfirm': { es: '¿Eliminar el comando rápido "{0}"?', en: 'Delete the quick command "{0}"?' },
	'openide.quickCommands.deleteButton': { es: 'Eliminar', en: 'Delete' },
	// ---- Rules
	'openide.rules.title': { es: 'Rules', en: 'Rules' },
	'openide.rules.desc': { es: 'Instrucciones Markdown obligatorias que se cargan completas en cada mensaje. Las Rules de proyecto reemplazan a las globales con el mismo nombre. El agente sólo puede modificarlas si se lo pedís explícitamente en ese turno.', en: 'Mandatory Markdown instructions loaded in full on every message. Project Rules replace global ones with the same name. The agent can only modify them if you ask it explicitly in that turn.' },
	'openide.rules.new': { es: 'Nueva Rule', en: 'New Rule' },
	'openide.rules.noProject': { es: 'No hay carpeta abierta', en: 'No folder open' },
	'openide.rules.noProjectDesc': { es: 'Abrí una carpeta, o elegí el ámbito User en la cabecera para administrar las Rules globales.', en: 'Open a folder, or pick the User scope in the header to manage global Rules.' },
	'openide.rules.loading': { es: 'Cargando Rules…', en: 'Loading Rules…' },
	'openide.rules.noMatch': { es: 'Ninguna Rule coincide', en: 'No Rule matches' },
	'openide.rules.tryOther': { es: 'Probá otra búsqueda.', en: 'Try another search.' },
	'openide.rules.emptyTitle': { es: 'Todavía no hay Rules en este ámbito', en: 'No Rules in this scope yet' },
	'openide.rules.emptyDesc': { es: 'Creá una instrucción concreta y verificable. Se aplica siempre, desde el próximo mensaje.', en: 'Write a concrete, checkable instruction. It applies always, from the next message on.' },
	'openide.rules.emptyRule': { es: '(regla vacía)', en: '(empty rule)' },
	'openide.rules.global': { es: 'Global', en: 'Global' },
	'openide.rules.project': { es: 'Proyecto', en: 'Project' },
	'openide.rules.open': { es: 'Abrir Rule', en: 'Open Rule' },
	'openide.rules.delete': { es: 'Eliminar Rule', en: 'Delete Rule' },
	'openide.rules.deleteConfirm': { es: '¿Eliminar la Rule "{0}"?', en: 'Delete the Rule "{0}"?' },
	'openide.rules.deleteDetail': { es: 'Dejará de formar parte de las instrucciones obligatorias del agente a partir del próximo mensaje.', en: 'It stops being part of the agent\'s mandatory instructions from the next message on.' },
	'openide.rules.deleteButton': { es: 'Eliminar', en: 'Delete' },
	'openide.rules.noProjectToast': { es: 'No hay carpeta abierta: elegí el ámbito User en la cabecera.', en: 'No folder open: pick the User scope in the header.' },
	'openide.rules.newPrompt': { es: 'Nombre de la Rule (kebab-case)', en: 'Rule name (kebab-case)' },
	'openide.rules.newPlaceholder': { es: 'ej: convenciones-ui, seguridad-deploy', en: 'e.g. ui-conventions, deploy-security' },
	'openide.rules.nameInvalid': { es: 'Usá kebab-case: letras minúsculas, números y guiones.', en: 'Use kebab-case: lowercase letters, numbers and hyphens.' },
	'openide.rules.exists': { es: 'Ya existe una Rule con ese nombre en este ámbito.', en: 'A Rule with that name already exists in this scope.' },
	// ---- Skills
	'openide.skills.import': { es: 'Importar carpeta…', en: 'Import folder…' },
	'openide.skills.new': { es: 'Crear manualmente…', en: 'Create manually…' },
	'openide.skills.install': { es: 'Instalar skill…', en: 'Install skill…' },
	'openide.skills.title': { es: 'Skills', en: 'Skills' },
	'openide.skills.desc': { es: 'Instrucciones reutilizables que el modelo carga sólo cuando son relevantes (no gastan contexto si no se usan). Apagar una la saca del índice sin borrarla.', en: 'Reusable instructions the model loads only when they are relevant (they cost no context if unused). Turning one off takes it out of the index without deleting it.' },
	'openide.skills.noProject': { es: 'No hay carpeta abierta', en: 'No folder open' },
	'openide.skills.noProjectDesc': { es: 'Abrí una carpeta, o elegí el ámbito User en la cabecera para administrar las skills globales.', en: 'Open a folder, or pick the User scope in the header to manage global skills.' },
	'openide.skills.loading': { es: 'Cargando skills…', en: 'Loading skills…' },
	'openide.skills.noMatch': { es: 'Ninguna skill coincide con la búsqueda.', en: 'No skill matches the search.' },
	'openide.skills.emptyTitle': { es: 'Todavía no hay skills', en: 'No skills yet' },
	'openide.skills.emptyDesc': { es: 'Instalá una desde skills.sh, GitHub o cualquier repositorio compatible; también podés importar una carpeta con SKILL.md o crear una plantilla propia.', en: 'Install one from skills.sh, GitHub or any compatible repository; you can also import a folder with a SKILL.md or create a template of your own.' },
	'openide.skills.disabled': { es: 'deshabilitada', en: 'disabled' },
	'openide.skills.noDesc': { es: '(sin descripción)', en: '(no description)' },
	'openide.skills.open': { es: 'Abrir SKILL.md', en: 'Open SKILL.md' },
	'openide.skills.delete': { es: 'Eliminar la skill', en: 'Delete the skill' },
	'openide.skills.reenable': { es: 'Reactivar (vuelve al índice del prompt)', en: 'Re-enable (returns to the prompt index)' },
	'openide.skills.disable': { es: 'Deshabilitar (sale del índice y de skill_view)', en: 'Disable (leaves the index and skill_view)' },
	'openide.skills.toggled': { es: 'Aplica a partir del próximo mensaje.', en: 'Applies from the next message on.' },
	'openide.skills.deleteConfirm': { es: '¿Eliminar la skill "{0}"?', en: 'Delete the skill "{0}"?' },
	'openide.skills.deleteDetail': { es: 'Se borra el directorio completo de esta skill (.openide/skills o .agents/skills).', en: 'The whole directory of this skill is deleted (.openide/skills or .agents/skills).' },
	'openide.skills.deleteButton': { es: 'Eliminar', en: 'Delete' },
	'openide.skills.deleteFailed': { es: 'No se pudo eliminar la skill "{0}".', en: 'Could not delete the skill "{0}".' },
	'openide.skills.noProjectToast': { es: 'No hay carpeta abierta: las skills viven en .openide/skills del proyecto.', en: 'No folder open: skills live in the project\'s .openide/skills.' },
	'openide.skills.newPrompt': { es: 'Nombre de la skill (kebab-case)', en: 'Skill name (kebab-case)' },
	'openide.skills.newPlaceholder': { es: 'ej: convenciones-api, revisar-migraciones', en: 'e.g. api-conventions, review-migrations' },
	'openide.skills.kebabInvalid': { es: 'kebab-case: a-z, 0-9 y guiones; sin -- ni guiones en los bordes.', en: 'kebab-case: a-z, 0-9 and hyphens; no -- and no hyphens at the edges.' },
	'openide.skills.exists': { es: 'Ya existe una skill con ese nombre.', en: 'A skill with that name already exists.' },
	'openide.skills.templateDesc': { es: 'Completá: qué hace esta skill y CUÁNDO usarla (con keywords)', en: 'Fill in: what this skill does and WHEN to use it (with keywords)' },
	'openide.skills.templateBody': { es: 'Instrucciones imperativas para el agente: pasos, ejemplos, convenciones.', en: 'Imperative instructions for the agent: steps, examples, conventions.' },
	'openide.skills.importTitle': { es: 'Elegí la carpeta de la skill (tiene que contener SKILL.md)', en: 'Pick the skill folder (it has to contain SKILL.md)' },
	'openide.skills.importLabel': { es: 'Importar skill', en: 'Import skill' },
	'openide.skills.importNoMd': { es: 'Esa carpeta no tiene un SKILL.md — no parece una skill.', en: 'That folder has no SKILL.md — it does not look like a skill.' },
	'openide.skills.importName': { es: 'Nombre para la skill (kebab-case)', en: 'Name for the skill (kebab-case)' },
	'openide.skills.importExists': { es: 'Ya existe la skill "{0}". ¿Reemplazarla?', en: 'The skill "{0}" already exists. Replace it?' },
	'openide.skills.replace': { es: 'Reemplazar', en: 'Replace' },
	'openide.skills.importOk': { es: 'Skill "{0}" importada. Entra al índice en el próximo mensaje.', en: 'Skill "{0}" imported. It enters the index on the next message.' },
} as const;
