/*---------------------------------------------------------------------------------------------
 *  Copyright (c) OpenIDE. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * The last surfaces that were still calling VS Code's `localize()`: the chat dock's composer,
 * pickers and transcript parts, the inline edit review's chrome, the plan breadcrumb's Build
 * split, the usage popover, and the agent contribution's commands and editor names.
 *
 * `localize()` is the wrong mechanism for anything the fork adds. It resolves against a language
 * PACK, and no pack in the world ships translations for keys that only exist here — so whatever is
 * written as the default is what every user sees, in every locale. That produced both halves of
 * the same bug on one screen: "Ejecutando…" and "Razonamiento" in Spanish for a user running the
 * IDE in English, and "Thinking" / "Keep File" in English for a user running it in Spanish.
 *
 * Every key here carries both languages and is read through `t()`, which resolves against the same
 * IDE locale `localize()` does. Spread into the same `STRINGS` object as the rest, so `t()` and
 * `OpenideStringKey` still see one flat dictionary.
 */
export const OPENIDE_CHAT_SURFACE_STRINGS = {
	// ---- resource cards
	'chatSurface.resource.web': { es: 'Vista previa web', en: 'Web preview' },
	'chatSurface.link.browser': { es: 'Abrir en navegador integrado', en: 'Open in browser' },
	'chatSurface.resource.open': { es: 'Abrir', en: 'Open' },
	'chatSurface.resource.openIn': { es: 'Abrir en…', en: 'Open in…' },
	'chatSurface.resource.panel': { es: 'Abrir en el panel', en: 'Open in workspace panel' },
	'chatSurface.resource.full': { es: 'Abrir vista completa', en: 'Open full view' },
	'chatSurface.resource.external': { es: 'Abrir en navegador externo', en: 'Open in external browser' },
	'chatSurface.resource.copy': { es: 'Copiar enlace', en: 'Copy link' },
	// ---- agent window
	'agentWindow.git.close': { es: 'Cerrar', en: 'Close' },
	'agentWindow.git.includeUnstaged': { es: 'Incluir cambios sin preparar', en: 'Include unstaged changes' },
	'agentWindow.git.commitPush': { es: 'Crear commit y enviar', en: 'Commit and push' },
	'agentWindow.git.scope': { es: 'Cambios a incluir', en: 'Changes to include' },
	'agentWindow.git.staged': { es: 'Preparados', en: 'Staged' },
	'agentWindow.git.all': { es: 'Todos los cambios', en: 'All changes' },
	'agentWindow.git.messagePlaceholder': { es: 'Describí qué cambió y por qué…', en: 'Describe what changed and why…' },
	'agentWindow.git.commitAction': { es: 'Crear commit', en: 'Commit' },
	'agentWindow.git.working': { es: 'Procesando…', en: 'Working…' },
	'agentWindow.git.clean': { es: 'No hay cambios pendientes. Podés enviar commits existentes.', en: 'No pending changes. You can push existing commits.' },
	'agentWindow.git.compareDirection': { es: 'Comparar una referencia base con {0}.', en: 'Compare a base reference with {0}.' },
	'agentWindow.git.findRef': { es: 'Buscar rama o etiqueta…', en: 'Search branches or tags…' },
	'agentWindow.git.base': { es: 'Referencia base', en: 'Base reference' },
	'agentWindow.git.review': { es: 'Revisar diferencias', en: 'Review differences' },
	'agentWindow.git.range': { es: '{0} → {1}', en: '{0} → {1}' },
	'agentWindow.git.noRefs': { es: 'No se encontraron referencias.', en: 'No matching references.' },
	'agentWindow.git.noRepository': { es: 'Este proyecto no tiene un repositorio Git disponible.', en: 'No Git repository is available for this project.' },
	'agentWindow.git.branchPlaceholder': { es: 'Seleccionar rama…', en: 'Select a branch…' },
	'agentWindow.git.comparePlaceholder': { es: 'Comparar la rama actual con…', en: 'Compare the current branch with…' },
	'agentWindow.git.currentBranch': { es: 'Rama actual', en: 'Current branch' },
	'agentWindow.git.noDifferences': { es: 'No hay diferencias entre estas referencias.', en: 'There are no differences between these references.' },
	'agentWindow.git.message': { es: 'Mensaje del commit', en: 'Commit message' },
	'agentWindow.git.messageRequired': { es: 'Escribí un mensaje antes de crear el commit.', en: 'Enter a message before committing.' },
	'agentWindow.git.stagedSummary': { es: '{0} preparados · {1} sin preparar', en: '{0} staged · {1} unstaged' },
	'agentWindow.git.commitStaged': { es: 'Crear commit de los cambios preparados', en: 'Commit staged changes' },
	'agentWindow.git.stageCommit': { es: 'Preparar cambios y crear commit', en: 'Stage changes and commit' },
	'agentWindow.git.push': { es: 'Enviar commits (push)', en: 'Push commits' },
	'agentWindow.git.conflicts': { es: 'Resolvé los {0} conflictos antes de crear el commit.', en: 'Resolve {0} conflicts before committing.' },
	'agentWindow.search': { es: 'Buscar conversaciones', en: 'Search conversations' },
	'agentWindow.searchPlaceholder': { es: 'Buscar conversaciones o proyectos…', en: 'Search conversations or projects…' },
	'agentWindow.searchActions': { es: 'Acciones rápidas', en: 'Quick actions' },
	'agentWindow.searchRecent': { es: 'Conversaciones recientes', en: 'Recent conversations' },
	'agentWindow.searchOpenFolder': { es: 'Abrir carpeta…', en: 'Open folder…' },
	'agentWindow.searchFilesPlaceholder': { es: 'Buscar archivos por nombre…', en: 'Search files by name…' },
	'agentWindow.searchFiles': { es: 'Buscar archivos…', en: 'Search files…' },
	'agentWindow.backToEnvironment': { es: 'Volver al entorno', en: 'Back to Environment' },
	'agentWindow.filesTitle': { es: "Archivos", en: "Files" },
	'agentWindow.conversations': { es: "Conversaciones", en: "Conversations" },
	'agentWindow.refresh': { es: "Actualizar", en: "Refresh" },
	'agentWindow.collapse': { es: "Contraer carpetas", en: "Collapse Folders" },
	'agentWindow.layout': { es: "Opciones de diseño", en: "Layout Options" },
	'agentWindow.focusChat': { es: "Centrar el chat", en: "Focus Chat" },
	'agentWindow.restoreLayout': { es: "Restaurar paneles", en: "Restore Panels" },
	'agentWindow.terminalNew': { es: "Nueva terminal", en: "New Terminal" },
	'agentWindow.terminalClose': { es: "Cerrar terminal", en: "Close Terminal" },
	'agentWindow.terminalEmpty': { es: "Abrí una terminal para trabajar en este proyecto.", en: "Open a terminal to work in this project." },
	'agentWindow.local': { es: "Local", en: "Local" },
	'agentWindow.commit': { es: "Commit o push", en: "Commit or Push" },
	'agentWindow.compare': { es: "Comparar rama", en: "Compare Branch" },
	'agentWindow.subagentsActive': { es: 'Activos', en: 'Active' },
	'agentWindow.subagentsDone': { es: 'Finalizados', en: 'Done' },
	'agentWindow.noActiveSubagents': { es: 'No hay subagentes activos', en: 'No active subagents' },
	'agentWindow.noCompletedSubagents': { es: 'No hay subagentes finalizados', en: 'No completed subagents' },
	'agentWindow.backToSubagents': { es: 'Volver a subagentes', en: 'Back to subagents' },
	'agentWindow.subagentRunning': { es: 'En curso', en: 'Running' },
	'agentWindow.subagentWaiting': { es: 'En espera', en: 'Waiting' },
	'agentWindow.subagentQueued': { es: 'En cola', en: 'Queued' },
	'agentWindow.subagentPreparing': { es: 'Preparando la conversación…', en: 'Preparing conversation…' },
	'agentWindow.subagentWorking': { es: 'Trabajando durante {0}', en: 'Working for {0}' },
	'agentWindow.subagentWorked': { es: 'Trabajó durante {0}', en: 'Worked for {0}' },
	'agentWindow.subagents': { es: "Subagentes", en: "Subagents" },
	'agentWindow.runningCount': { es: '{0} en curso', en: '{0} working' },
	'chat.subagents.and': { es: '{0} y {1}', en: '{0} and {1}' },
	'chat.subagents.more': { es: '{0} y {1} más', en: '{0} and {1} more' },
	'chat.subagents.started': { es: '{0} empezaron a trabajar', en: '{0} started working' },
	'chat.subagents.startedOne': { es: '{0} empezó a trabajar', en: '{0} started working' },
	'chat.subagents.done': { es: '{0} terminaron', en: '{0} finished' },
	'chat.subagents.doneOne': { es: '{0} terminó', en: '{0} finished' },
	'chat.subagents.status': { es: '{0} · {1}', en: '{0} · {1}' },
	'chat.subagents.failed': { es: '{0} con error', en: '{0} failed' },
	'chat.subagents.cancelled': { es: '{0} cancelados', en: '{0} cancelled' },
	'agentWindow.doneCount': { es: '{0} finalizados', en: '{0} done' },
	'agentWindow.processes': { es: "Procesos en segundo plano", en: "Background Processes" },
	'agentWindow.sources': { es: "Fuentes", en: "Sources" },
	'agentWindow.noChanges': { es: "Sin cambios pendientes", en: "No pending changes" },
	'agentWindow.noSubagents': { es: "No hay subagentes en esta conversación", en: "No subagents in this conversation" },
	'agentWindow.noProcesses': { es: "No hay terminales en ejecución", en: "No running terminals" },
	'agentWindow.noSources': { es: "No hay fuentes adjuntas", en: "No attached sources" },
	'agentWindow.imageSource': { es: "Imagen {0}", en: "Image {0}" },
	'agentWindow.branch': { es: 'Rama actual', en: 'Current branch' },
	'agentWindow.open': { es: 'OpenIDE Agent: Abrir ventana agéntica', en: 'OpenIDE Agent: Open Agent Window' },
	'agentWindow.workspace': { es: 'Espacio de trabajo', en: 'Workspace' },
	'agentWindow.label': { es: 'Ventana agéntica de OpenIDE', en: 'OpenIDE Agent Window' },
	'agentWindow.harness': { es: 'Elegir harness', en: 'Choose harness' },
	'agentWindow.browser': { es: 'Navegador', en: 'Browser' },
	'agentWindow.settings': { es: 'Configuración', en: 'Settings' },
	'agentWindow.toggleSidebar': { es: 'Mostrar u ocultar conversaciones', en: 'Toggle conversations' },
	'agentWindow.toggleContext': { es: 'Mostrar u ocultar contexto', en: 'Toggle context' },
	'agentWindow.toggleChanges': { es: 'Mostrar u ocultar archivos modificados', en: 'Toggle Changed Files' },
	'agentWindow.contextTitle': { es: 'Contexto', en: 'Context' },
	'agentWindow.workspacePanel': { es: 'Panel de trabajo', en: 'Workspace panel' },
	'agentWindow.workspaceEmpty': { es: 'Abrí una herramienta o un archivo para continuar.', en: 'Open a tool or file to continue.' },
	'agentWindow.toggleWorkspace': { es: 'Mostrar u ocultar panel de trabajo', en: 'Toggle workspace panel' },
	'agentWindow.openView': { es: 'Abrir vista', en: 'Open view' },
	'agentWindow.continueConversation': { es: 'Continuar en el chat principal', en: 'Continue in main chat' },
	'agentWindow.openViews': { es: 'Vistas abiertas', en: 'Open views' },
	'agentWindow.noOpenViews': { es: 'Las vistas minimizadas aparecerán aquí.', en: 'Minimized views will appear here.' },
	'agentWindow.openModal': { es: 'Abrir en modal', en: 'Open in modal' },
	'agentWindow.dockView': { es: 'Volver al panel de trabajo', en: 'Return to workspace panel' },
	'agentWindow.minimizeView': { es: 'Minimizar al entorno', en: 'Minimize to environment' },
	'agentWindow.environment': { es: 'Entorno', en: 'Environment' },
	'agentWindow.terminal': { es: 'Terminal', en: 'Terminal' },
	'agentWindow.contextUsage': { es: 'Uso de contexto', en: 'Context usage' },
	'agentWindow.reviewChanges': { es: 'Revisar cambios', en: 'Review changes' },
	'agentWindow.changesFilter': { es: 'Filtrar archivos modificados', en: 'Filter changed files' },
	'agentWindow.noMatchingChanges': { es: 'No hay archivos coincidentes', en: 'No matching files' },
	'agentWindow.changesCount': { es: '{0} archivos modificados', en: '{0} changed files' },

	// ---- composer
	'chatSurface.composer.placeholder': { es: 'Plan, Build, / para skills, @ para contexto', en: 'Plan, Build, / for skills, @ for context' },
	'chatSurface.composer.aria': { es: 'Mensaje del chat de OpenIDE', en: 'OpenIDE chat message' },
	'chatSurface.composer.suggestHint': { es: '/{0} {1}', en: '/{0} {1}' },

	// ---- the model chip in the composer
	'chatSurface.model.loading': { es: 'Cargando modelos…', en: 'Loading models…' },
	'chatSurface.model.unset': { es: 'Seleccionar modelo', en: 'Select model' },
	'chatSurface.model.fallback': { es: 'Modelo', en: 'Model' },

	// ---- queued messages
	'chatSurface.queue.image': { es: '(imagen)', en: '(image)' },
	'chatSurface.queue.one': { es: '1 pendiente', en: '1 queued' },
	'chatSurface.queue.many': { es: '{0} pendientes', en: '{0} queued' },

	// ---- voice dictation
	'chatSurface.voice.unsupported': { es: 'El proveedor activo no permite dictado por voz.', en: 'The active provider does not support voice dictation.' },
	'chatSurface.voice.usingModel': { es: '{0} · {1} · {2}', en: '{0} · {1} · {2}' },
	'chatSurface.voice.configure': { es: 'Configurar el dictado', en: 'Set up dictation' },
	'chatSurface.voice.startFailed': { es: 'No se pudo iniciar el dictado', en: 'Could not start dictation' },
	'chatSurface.voice.listening': { es: 'Micrófono activo · Escuchando…', en: 'Microphone on · Listening…' },
	'chatSurface.voice.permissionDenied': { es: 'Permití el acceso al micrófono en los ajustes de privacidad del sistema y volvé a intentar.', en: 'Allow microphone access in system privacy settings and try again.' },
	'chatSurface.voice.noMicrophone': { es: 'No se encontró un micrófono. Conectá uno y volvé a intentar.', en: 'No microphone found. Connect one and try again.' },
	'chatSurface.voice.deviceBusy': { es: 'No se pudo acceder al micrófono. Revisá el dispositivo o si otra aplicación lo está usando.', en: 'Could not access the microphone. Check the device or whether another app is using it.' },
	'chatSurface.voice.cancel': { es: 'Cancelar grabación. El texto ya transcrito se conserva.', en: 'Cancel recording. Already transcribed text is kept.' },
	'chatSurface.voice.review': { es: 'Detener y revisar la transcripción', en: 'Stop and review transcription' },
	'chatSurface.voice.send': { es: 'Detener, transcribir y enviar', en: 'Stop, transcribe and send' },
	'chatSurface.voice.label': { es: 'Dictado', en: 'Dictation' },

	// ---- reasoning effort: the menu's heading and the two levels that are not proper names.
	// "Minimal", "Low", "Medium", "High", "Extra High" and "Max" stay identical in both languages
	// on purpose — they are the API's own values, and a user reading a provider's docs should find
	// the same word in the menu.
	'chatSurface.effort.range': { es: 'Más rápido · Más razonamiento', en: 'Faster · More reasoning' },
	'chatSurface.fast.tip': { es: 'Modo rápido: procesamiento prioritario; puede aumentar el consumo. La velocidad depende del proveedor.', en: 'Fast mode: priority processing may increase usage. Speed depends on the provider.' },
	'chatSurface.fast.unavailable': { es: 'Este modelo no ofrece procesamiento prioritario en el proveedor conectado.', en: 'This model does not offer priority processing through the connected provider.' },
	'chatSurface.effort.reset': { es: 'Restablecer esfuerzo', en: 'Reset effort' },
	'chatSurface.effort.advanced': { es: 'Avanzado', en: 'Advanced' },
	'chatSurface.effort.section': { es: 'Razonamiento', en: 'Reasoning' },
	'chatSurface.effort.default': { es: 'Default del modelo', en: 'Model default' },
	'chatSurface.effort.none': { es: 'Sin razonamiento', en: 'No reasoning' },
	'chatSurface.effort.minimal': { es: 'Minimal', en: 'Minimal' },
	'chatSurface.effort.low': { es: 'Low', en: 'Low' },
	'chatSurface.effort.medium': { es: 'Medium', en: 'Medium' },
	'chatSurface.effort.high': { es: 'High', en: 'High' },
	'chatSurface.effort.xhigh': { es: 'Extra High', en: 'Extra High' },
	'chatSurface.effort.max': { es: 'Max', en: 'Max' },

	// ---- transcript list (screen-reader labels)
	'chatSurface.list.widget': { es: 'Transcripción del chat de OpenIDE', en: 'OpenIDE chat transcript' },
	'chatSurface.list.request': { es: 'Vos: {0}', en: 'You: {0}' },
	'chatSurface.list.response': { es: 'Asistente: {0}', en: 'Assistant: {0}' },

	// ---- mode and permission picker
	'chatSurface.mode.section': { es: 'Modo', en: 'Mode' },
	'chatSurface.mode.agent': { es: 'Edita y ejecuta', en: 'Edit and run' },
	'chatSurface.mode.plan': { es: 'Planificación en solo lectura', en: 'Read-only planning' },
	'chatSurface.mode.ask': { es: 'Preguntas y respuestas en solo lectura', en: 'Read-only Q&A' },
	'chatSurface.mode.debug': { es: 'Reproduce y corrige', en: 'Reproduce and fix' },
	'chatSurface.permission.section': { es: 'Permisos', en: 'Permissions' },
	'chatSurface.permission.ask': { es: 'Preguntar siempre', en: 'Always ask' },
	'chatSurface.permission.autoEdit': { es: 'Auto-aprobar ediciones', en: 'Auto-approve edits' },
	'chatSurface.permission.autoEditDesc': { es: 'Las ediciones de archivo se aplican solas; la terminal sigue preguntando.', en: 'File edits apply on their own; the terminal still asks.' },
	'chatSurface.permission.autoAll': { es: 'Auto-aprobar todo', en: 'Auto-approve everything' },
	'chatSurface.permission.autoAllDesc': { es: 'Todo se ejecuta sin preguntar, salvo lo peligroso y los archivos sensibles.', en: 'Everything runs without asking, except what is dangerous and sensitive files.' },

	// ---- model detail card
	'chatSurface.model.tools': { es: 'Uso de herramientas', en: 'Tool use' },
	'chatSurface.model.reasoning': { es: 'Razonamiento', en: 'Reasoning' },
	'chatSurface.model.capabilities': { es: 'Capacidades', en: 'Capabilities' },
	'chatSurface.model.input': { es: 'Entrada', en: 'Input' },
	'chatSurface.model.output': { es: 'Salida', en: 'Output' },
	'chatSurface.model.cost': { es: 'Costo ($/1M tokens)', en: 'Cost ($/1M tokens)' },

	// ---- model picker
	'chatSurface.model.search': { es: 'Buscar modelos…', en: 'Search models…' },
	'chatSurface.model.favorites': { es: 'Favoritos', en: 'Favorites' },
	'chatSurface.model.recents': { es: 'Recientes', en: 'Recent' },
	'chatSurface.model.noResults': { es: 'Sin resultados', en: 'No results' },
	'chatSurface.model.noProviders': { es: 'Sin proveedores conectados', en: 'No providers connected' },
	'chatSurface.model.star': { es: 'Marcar como favorito', en: 'Add to favorites' },
	'chatSurface.model.unstar': { es: 'Quitar de favoritos', en: 'Remove from favorites' },

	// ---- transcript parts
	'chatSurface.response.cancelled': { es: 'Turno cancelado.', en: 'Turn cancelled.' },
	'chatSurface.explore.error': { es: '{0} — error', en: '{0} — error' },
	'chatSurface.thinking': { es: 'Pensando', en: 'Thinking' },
	'chatSurface.thoughtBriefly': { es: 'Pensó un momento', en: 'Thought briefly' },
	'chatSurface.thoughtFor': { es: 'Pensó {0} s', en: 'Thought for {0}s' },
	'chatSurface.tool.cancelled': { es: 'Cancelado', en: 'Cancelled' },
	'chatSurface.tool.failed': { es: 'Falló', en: 'Failed' },
	'chatSurface.tool.result': { es: 'Resultado', en: 'Result' },
	'chatSurface.subagent.toolFailed': { es: 'Falló una herramienta', en: 'A tool failed' },
	'chatSurface.subagent.denied': { es: 'Permiso denegado', en: 'Permission denied' },
	'chatSurface.subagent.failed': { es: 'El especialista falló', en: 'The specialist failed' },

	// ---- inline approval card
	'chatSurface.approval.waiting': { es: 'Esperando tu aprobación', en: 'Waiting for your approval' },
	'chatSurface.approval.review': { es: 'Acción que requiere aprobación', en: 'Action requiring approval' },
	'chatSurface.approval.scope': { es: 'Permiso', en: 'Permission' },
	'chatSurface.approval.scopeOnce': { es: 'Solo esta vez', en: 'Only this time' },
	'chatSurface.approval.scopeSession': { es: 'Durante esta sesión', en: 'For this session' },
	'chatSurface.approval.scopeAlways': { es: 'Recordar permiso', en: 'Remember permission' },
	'chatSurface.approval.scopeCommandHint': { es: 'Se reutiliza el permiso para este comando.', en: 'Permission is reused for this command.' },
	'chatSurface.approval.scopeToolHint': { es: 'Se aplica a otras acciones de esta herramienta. Las rutas sensibles siguen pidiendo aprobación.', en: 'Applies to other actions by this tool. Sensitive paths still require approval.' },
	'chatSurface.approval.allow': { es: 'Permitir', en: 'Allow' },
	'chatSurface.approval.always': { es: 'Permitir siempre', en: 'Always allow' },
	'chatSurface.approval.deny': { es: 'Rechazar', en: 'Deny' },
	'chatSurface.approval.allowed': { es: 'Permitido', en: 'Allowed' },
	'chatSurface.approval.allowedAlways': { es: 'Permitido siempre', en: 'Always allowed' },
	'chatSurface.approval.denied': { es: 'Rechazado', en: 'Denied' },

	// ---- approval quick pick (the codicon prefixes are markup, not copy)
	'chatSurface.approve.once': { es: '$(check) Permitir una vez', en: '$(check) Allow once' },
	'chatSurface.approve.always': { es: '$(star-full) Permitir siempre', en: '$(star-full) Always allow' },
	'chatSurface.approve.sensitiveNote': { es: '(no disponible: path sensible)', en: '(unavailable: sensitive path)' },
	'chatSurface.approve.deny': { es: '$(x) Rechazar', en: '$(x) Deny' },
	'chatSurface.approve.execPlaceholder': { es: 'El agente quiere ejecutar: {0}', en: 'The agent wants to run: {0}' },
	'chatSurface.approve.usePlaceholder': { es: 'El agente quiere usar {0}', en: 'The agent wants to use {0}' },

	// ---- inline edit review (editor chrome)
	'chatSurface.review.prevBlock': { es: 'Bloque anterior', en: 'Previous block' },
	'chatSurface.review.nextBlock': { es: 'Bloque siguiente', en: 'Next block' },
	'chatSurface.review.undoBlock': { es: 'Deshacer', en: 'Undo' },
	'chatSurface.review.keepBlock': { es: 'Conservar', en: 'Keep' },
	'chatSurface.review.prevFile': { es: 'Archivo anterior', en: 'Previous file' },
	'chatSurface.review.nextFile': { es: 'Archivo siguiente', en: 'Next file' },
	'chatSurface.review.undoFile': { es: 'Deshacer archivo', en: 'Undo File' },
	'chatSurface.review.undoFileTip': { es: 'Deshacer todos los cambios del agente en este archivo', en: 'Undo all agent changes in this file' },
	'chatSurface.review.keepFile': { es: 'Conservar archivo', en: 'Keep File' },
	'chatSurface.review.keepFileTip': { es: 'Conservar todos los cambios del agente en este archivo', en: 'Keep all agent changes in this file' },
	'chatSurface.review.fileOf': { es: '{0} de {1} archivos', en: '{0} of {1} Files' },
	'chatSurface.review.oneFile': { es: '1 de 1 archivo', en: '1 of 1 File' },
	'chatSurface.review.blockOf': { es: '{0} de {1}', en: '{0} of {1}' },
	'chatSurface.review.noBlocks': { es: '0 de 0', en: '0 of 0' },

	// ---- plan breadcrumb's Build split
	'chatSurface.plan.modelPicker': { es: 'Modelo con el que se ejecuta el plan', en: 'Model the plan runs with' },
	'chatSurface.plan.modelSaveError': { es: 'No se pudo guardar el modelo del plan: {0}', en: 'Could not save the plan model: {0}' },
	'chatSurface.plan.modelUnset': { es: 'Elegir modelo', en: 'Pick model' },
	'chatSurface.plan.running': { es: 'Ejecutando…', en: 'Running…' },
	'chatSurface.plan.completed': { es: 'Finalizado', en: 'Done' },
	'chatSurface.plan.build': { es: 'Ejecutar el plan', en: 'Run the plan' },
	'chatSurface.plan.runAgain': { es: 'Ejecutar de nuevo', en: 'Run again' },
	'chatSurface.plan.openChat': { es: 'Abrir el chat', en: 'Open the chat' },

	// ---- usage popover
	'chatSurface.usage.title': { es: 'Uso', en: 'Usage' },
	'chatSurface.usage.refresh': { es: 'Actualizar ahora', en: 'Refresh now' },
	'chatSurface.usage.details': { es: 'Detalles de uso', en: 'Usage details' },
	'chatSurface.usage.accounts': { es: 'Administrar cuentas…', en: 'Manage accounts…' },
	'chatSurface.usage.updating': { es: 'actualizando…', en: 'updating…' },
	'chatSurface.usage.updatedAgo': { es: 'actualizado {0}', en: 'updated {0}' },
	'chatSurface.usage.loading': { es: 'Consultando las cuentas…', en: 'Querying the accounts…' },
	'chatSurface.usage.noAccounts': { es: 'No hay cuentas conectadas.', en: 'No accounts connected.' },
	'chatSurface.usage.balance': { es: 'Saldo', en: 'Balance' },
	'chatSurface.usage.spent': { es: '{0} gastados', en: '{0} spent' },
	'chatSurface.usage.noData': { es: 'Sin datos de uso', en: 'No usage data' },
	'chatSurface.usage.retry': { es: 'reintenta {0}', en: 'retry {0}' },

	// ---- the status bar entry (openideChatView)
	'chatSurface.status.working': { es: 'Trabajando…', en: 'Working…' },
	'chatSurface.status.workingAria': { es: 'OpenIDE Agent: trabajando', en: 'OpenIDE Agent: working' },
	'chatSurface.status.noProviderShort': { es: 'sin proveedor', en: 'no provider' },
	'chatSurface.status.connect': { es: 'Conectar proveedor de IA', en: 'Connect an AI provider' },
	'chatSurface.status.connectAria': { es: 'OpenIDE Agent: sin proveedor conectado', en: 'OpenIDE Agent: no provider connected' },
	'chatSurface.status.connectTooltip': { es: 'No hay proveedor de IA conectado — abrí la página de proveedores para conectar una cuenta o API key.', en: 'No AI provider is connected — open the providers page to connect an account or API key.' },

	// ---- editor names and commands of the agent contribution. "Project Map", "Plan" and "Canvas"
	// are the editors' own names and stay identical in both languages.
	'chatSurface.editor.projectMap': { es: 'Project Map', en: 'Project Map' },
	'chatSurface.editor.plan': { es: 'Plan', en: 'Plan' },
	'chatSurface.editor.subagent': { es: 'Subagente', en: 'Subagent' },
	'chatSurface.editor.canvas': { es: 'Canvas', en: 'Canvas' },
	'chatSurface.container.chat': { es: 'OpenIDE Chat', en: 'OpenIDE Chat' },
	'chatSurface.cmd.memoryOpen': { es: 'OpenIDE: Abrir Project Map', en: 'OpenIDE: Open Project Map' },
	'chatSurface.cmd.memoryRebuild': { es: 'OpenIDE: Reconstruir la memoria del codebase', en: 'OpenIDE: Rebuild Codebase Memory' },
	'chatSurface.cmd.memoryClear': { es: 'OpenIDE: Borrar la memoria del codebase', en: 'OpenIDE: Clear Codebase Memory' },
	'chatSurface.cmd.memoryStatus': { es: 'OpenIDE: Estado de la memoria del codebase', en: 'OpenIDE: Codebase Memory Status' },
	'chatSurface.cmd.subagentCreate': { es: 'OpenIDE: Crear subagente', en: 'OpenIDE: Create Subagent' },
	'chatSurface.cmd.subagentOpenEditor': { es: 'OpenIDE: Abrir el editor de subagentes', en: 'OpenIDE: Open Subagent Editor' },
	'chatSurface.cmd.subagentOpenText': { es: 'OpenIDE: Abrir el subagente como texto', en: 'OpenIDE: Open Subagent as Text' },
	'chatSurface.mcp.reloadDone': { es: 'MCP: {0}', en: 'MCP: {0}' },
	'chatSurface.language.migrate': { es: 'OpenIDE ahora usa un solo idioma para toda la interfaz. ¿Cambiar la IDE a {0}?', en: 'OpenIDE now uses a single display language for the whole interface. Switch the IDE to {0}?' },
	'chatSurface.language.migrateYes': { es: 'Cambiar el idioma de la interfaz', en: 'Change display language' },
	'chatSurface.language.deprecatedDesc': { es: 'Obsoleto. OpenIDE ahora dibuja sus propias pantallas en el idioma de la interfaz, así que Configuración › Idioma mueve todo a la vez.', en: 'Deprecated. OpenIDE now renders its own screens in the display language, so Settings › Language moves the whole interface at once.' },
	'chatSurface.language.deprecatedMessage': { es: 'Usá el idioma de la interfaz (Configuración › Idioma). OpenIDE lo sigue para sus propias pantallas.', en: 'Use the display language instead (Settings › Language). OpenIDE follows it for its own screens.' },
	'chat.empty.start': { es: '¿En qué querés trabajar?', en: 'What would you like to work on?' },
	// ---- fork-owned goal, Canvas, activity, review, and navigation surfaces
	'codexGoal.approval': { es: 'Codex requiere tu aprobación', en: 'Codex Requires Your Approval' },
	'codexGoal.approve': { es: 'Permitir una vez', en: 'Allow Once' },
	'goal.acceptRevision': { es: 'Aceptar criterios revisados del objetivo', en: 'Accept Revised Goal Criteria' },
	'goal.active': { es: 'Activo', en: 'Active' },
	'goal.announcement': { es: '{0}. {1} de {2} criterios verificados.', en: '{0}. {1} of {2} criteria verified.' },
	'goal.blocked': { es: 'Bloqueado', en: 'Blocked' },
	'goal.cancel': { es: 'Cancelar objetivo', en: 'Cancel Goal' },
	'goal.cancelled': { es: 'Cancelado', en: 'Cancelled' },
	'goal.changes': { es: 'Cambios', en: 'Changes' },
	'goal.chooseChange': { es: 'Revisar cambios capturados durante este objetivo', en: 'Review changes captured during this goal' },
	'goal.cli': { es: 'Seguimiento por CLI: OpenIDE conserva el contrato y los informes. La continuación automática requiere un adaptador verificado; el silencio de la terminal no inicia otro turno.', en: 'CLI tracking: OpenIDE keeps the contract and reports. Automatic continuation requires a verified adapter; terminal silence does not start another turn.' },
	'goal.cliReady': { es: 'Codex está conectado. OpenIDE puede continuar este objetivo mediante eventos de turno verificados.', en: 'Codex is connected. OpenIDE can continue this goal through verified turn events.' },
	'goal.completed': { es: 'Completado', en: 'Completed' },
	'goal.confirm': { es: 'Confirmá tu revisión', en: 'Confirm Your Review' },
	'goal.confirmDetail': { es: 'Confirmá que revisaste el resultado actual y que este criterio se cumple:\n\n{0}\n\nEsto registra tu revisión manual; no afirma que una prueba automática haya pasado.', en: 'Confirm that you inspected the current result and this criterion is satisfied:\n\n{0}\n\nThis records your manual review; it does not claim an automated test passed.' },
	'goal.count': { es: '{0}/{1} verificados', en: '{0}/{1} verified' },
	'goal.create': { es: 'Crear objetivo', en: 'Create Goal' },
	'goal.criteria': { es: 'Criterios de finalización', en: 'Completion Criteria' },
	'goal.criteriaExample': { es: 'Las pruebas pasan :: npm test ;; Revisar la interfaz', en: 'Tests pass :: npm test ;; Review the interface' },
	'goal.criteriaPrompt': { es: 'Separá los criterios con ;;. Comando de verificación opcional: criterio :: comando. Los criterios sin comando requieren tu revisión explícita.', en: 'Separate criteria with ;;. Optional verification command: criterion :: command. Criteria without a command need your explicit review.' },
	'goal.criteriaRequired': { es: 'Ingresá al menos un criterio.', en: 'Enter at least one criterion.' },
	'goal.evidence': { es: 'Evidencia · {0}', en: 'Evidence · {0}' },
	'goal.extendLimit': { es: 'El objetivo usó {0} turnos. Establecé un límite total mayor para continuar.', en: 'Goal used {0} turns. Set a larger total turn limit to continue.' },
	'goal.failed': { es: 'Falló', en: 'Failed' },
	'goal.fromPlan': { es: 'Ejecutar como objetivo', en: 'Run as Goal' },
	'goal.heading': { es: 'Objetivo · {0}', en: 'Goal · {0}' },
	'goal.interrupted': { es: 'Interrumpido', en: 'Interrupted' },
	'goal.invalidLimit': { es: 'Ingresá un número entero mayor que {0}, hasta 1000.', en: 'Enter a whole number greater than {0}, up to 1000.' },
	'goal.keepRevision': { es: 'Mantener objetivo en pausa', en: 'Keep Goal Paused' },
	'goal.limit': { es: 'Límite alcanzado', en: 'Limit Reached' },
	'goal.local': { es: 'Los objetivos requieren un workspace local.', en: 'Goals require a local workspace.' },
	'goal.mapCommunity': { es: 'Objetivos', en: 'Goals' },
	'goal.mapName': { es: 'Objetivo: {0}', en: 'Goal: {0}' },
	'goal.mapProvenance': { es: 'Derivado de GOAL.md y REPORT.md. Estos documentos se pueden editar; abrí la conversación para inspeccionar el estado actual de ejecución.', en: 'Derived from GOAL.md and REPORT.md. These documents can be edited; open the conversation to inspect the current execution state.' },
	'goal.mapState': { es: 'Estado informado del objetivo: {0}', en: 'Reported Goal State: {0}' },
	'goal.nativeChange': { es: 'Edición nativa capturada', en: 'Captured native edit' },
	'goal.objective': { es: '¿Qué resultado debe seguir buscando OpenIDE?', en: 'What result should OpenIDE keep working toward?' },
	'goal.observed': { es: 'Atribución incierta', en: 'Attribution uncertain' },
	'goal.pause': { es: 'Pausar', en: 'Pause' },
	'goal.paused': { es: 'En pausa', en: 'Paused' },
	'goal.pauseDetail': { es: 'La pausa evita nuevos turnos. Una operación en curso todavía puede terminar.', en: 'Pause prevents further turns. A running operation may still finish.' },
	'goal.pauseReview': { es: 'Pausá el objetivo antes de confirmar un criterio.', en: 'Pause the goal before confirming a criterion.' },
	'goal.required': { es: 'Ingresá un resultado concreto.', en: 'Enter a concrete result.' },
	'goal.resume': { es: 'Reanudar', en: 'Resume' },
	'goal.review': { es: 'Revisar', en: 'Review' },
	'goal.reviewed': { es: 'Registrar mi revisión', en: 'Record My Review' },
	'goal.reviewRevision': { es: 'Los criterios modificados invalidan la evidencia anterior. Revisá GOAL.md antes de aceptar.', en: 'Changed criteria invalidate earlier evidence. Review GOAL.md before accepting.' },
	'goal.snapshotChanged': { es: 'Esta instantánea del objetivo cambió. Abrí de nuevo los cambios del objetivo para revisar la versión actual.', en: 'This goal snapshot changed. Open Goal Changes again to review the current snapshot.' },
	'goal.snapshotInvalid': { es: 'Referencia de instantánea del objetivo no válida.', en: 'Invalid goal snapshot reference.' },
	'goal.suggestion': { es: 'Definir un objetivo persistente y verificar su finalización', en: 'Set a persistent goal and verify its completion' },
	'goal.tray': { es: 'Objetivo', en: 'Goal' },
	'goal.turnLimit': { es: 'Máximo de turnos', en: 'Maximum Turns' },
	'goal.turnLimitPrompt': { es: 'OpenIDE detiene la continuación automática al llegar a este límite. Podés pausar o cancelar en cualquier momento.', en: 'OpenIDE stops automatic continuation at this limit. Pausing or cancelling remains available at any time.' },
	'goal.turnLimitValid': { es: 'Ingresá un número entero entre 1 y 100.', en: 'Enter a whole number between 1 and 100.' },
	'goal.turns': { es: 'Turnos: {0}/{1}', en: 'Turns: {0}/{1}' },
	'openide.activity.browser': { es: 'Usó el navegador', en: 'Used browser' },
	'openide.activity.completed': { es: 'Acciones completadas', en: 'Completed actions' },
	'openide.activity.details': { es: 'Mostrar detalles de actividad', en: 'Show Activity Details' },
	'openide.activity.ran': { es: 'Ejecutó comandos', en: 'Ran commands' },
	'openide.activity.read': { es: 'Leyó archivos', en: 'Read files' },
	'openide.activity.readRan': { es: 'Leyó archivos y ejecutó comandos', en: 'Read files, ran commands' },
	'openide.activity.thought': { es: 'Razonó', en: 'Thought' },
	'openide.activity.tools': { es: 'Usó herramientas', en: 'Used tools' },
	'openide.agentWindow.command': { es: 'Agentes: {0}', en: 'Agents: {0}' },
	'openide.canvas.3d_scene': { es: 'Escena 3D', en: '3D Scene' },
	'openide.canvas.add_screen': { es: 'Añadir pantalla', en: 'Add screen' },
	'openide.canvas.animation': { es: 'Animación', en: 'Animation' },
	'openide.canvas.capture_editor': { es: 'Capturar editor', en: 'Capture editor' },
	'openide.canvas.color_token': { es: 'Token de color', en: 'Color token' },
	'openide.canvas.comment': { es: 'Comentario', en: 'Comment' },
	'openide.canvas.create_canvas': { es: 'Crear Canvas', en: 'Create Canvas' },
	'openide.canvas.create_goal': { es: 'Crear GOAL', en: 'Create GOAL' },
	'openide.canvas.delete_element': { es: 'Eliminar elemento', en: 'Delete element' },
	'openide.canvas.delete_keyframe': { es: 'Eliminar fotograma clave', en: 'Delete Keyframe' },
	'openide.canvas.delete_screen': { es: 'Eliminar pantalla', en: 'Delete screen' },
	'openide.canvas.design': { es: 'Diseño', en: 'Design' },
	'openide.canvas.destination': { es: 'Destino', en: 'Destination' },
	'openide.canvas.device': { es: 'Dispositivo', en: 'Device' },
	'openide.canvas.draw': { es: 'Dibujar', en: 'Draw' },
	'openide.canvas.duplicate_variant': { es: 'Duplicar variante', en: 'Duplicate variant' },
	'openide.canvas.duration': { es: 'Duración', en: 'Duration' },
	'openide.canvas.export_format': { es: 'Formato de exportación', en: 'Export format' },
	'openide.canvas.export_html': { es: 'Exportar HTML', en: 'Export HTML' },
	'openide.canvas.fidelity': { es: 'Fidelidad', en: 'Fidelity' },
	'openide.canvas.file_delivery': { es: 'Archivo y entrega', en: 'File & delivery' },
	'openide.canvas.frame_height': { es: 'Alto del marco', en: 'Frame height' },
	'openide.canvas.frame_rotation': { es: 'Rotación del marco', en: 'Frame rotation' },
	'openide.canvas.frame_width': { es: 'Ancho del marco', en: 'Frame width' },
	'openide.canvas.frame_x': { es: 'X del marco', en: 'Frame x' },
	'openide.canvas.frame_y': { es: 'Y del marco', en: 'Frame y' },
	'openide.canvas.implementation_file': { es: 'Archivo de implementación', en: 'Implementation file' },
	'openide.canvas.import_image': { es: 'Importar imagen', en: 'Import Image' },
	'openide.canvas.import_obj': { es: 'Importar OBJ', en: 'Import OBJ' },
	'openide.canvas.import_tokens': { es: 'Importar tokens', en: 'Import Tokens' },
	'openide.canvas.keyframe_opacity': { es: 'Opacidad del fotograma clave', en: 'Keyframe opacity' },
	'openide.canvas.keyframe_rotation': { es: 'Rotación del fotograma clave', en: 'Keyframe rotation' },
	'openide.canvas.keyframe_scale': { es: 'Escala del fotograma clave', en: 'Keyframe scale' },
	'openide.canvas.keyframe_x': { es: 'X del fotograma clave', en: 'Keyframe x' },
	'openide.canvas.keyframe_y': { es: 'Y del fotograma clave', en: 'Keyframe y' },
	'openide.canvas.move_to_top_of_screen': { es: 'Mover al inicio de la pantalla', en: 'Move to top of screen' },
	'openide.canvas.on_click': { es: 'Al hacer clic', en: 'On click' },
	'openide.canvas.pause_motion': { es: 'Pausar movimiento', en: 'Pause Motion' },
	'openide.canvas.play': { es: 'Reproducir', en: 'Play' },
	'openide.canvas.play_motion': { es: 'Reproducir movimiento', en: 'Play Motion' },
	'openide.canvas.position_x': { es: 'posición X', en: 'position X' },
	'openide.canvas.position_y': { es: 'posición Y', en: 'position Y' },
	'openide.canvas.position_z': { es: 'posición Z', en: 'position Z' },
	'openide.canvas.prepare_plan': { es: 'Preparar plan', en: 'Prepare Plan' },
	'openide.canvas.primitive': { es: 'Primitiva', en: 'Primitive' },
	'openide.canvas.project_title': { es: 'Título del proyecto', en: 'Project title' },
	'openide.canvas.redo': { es: 'Rehacer', en: 'Redo' },
	'openide.canvas.request.0': { es: '¿Qué querés crear?', en: 'What should we create?' },
	'openide.canvas.request.1': { es: 'Elegí un formato y llevalo al chat. Podés añadir detalles antes de enviarlo.', en: 'Choose a format and take it to chat. You can add details before sending.' },
	'openide.canvas.request.2': { es: 'Formato de Canvas', en: 'Canvas format' },
	'openide.canvas.request.3': { es: 'Título del proyecto (opcional)', en: 'Project title (optional)' },
	'openide.canvas.request.4': { es: '¿Qué querés crear? (opcional)', en: 'What do you want to create? (optional)' },
	'openide.canvas.request.5': { es: 'Continuar en el chat', en: 'Continue in chat' },
	'openide.canvas.requestPrompt': { es: 'Creá un Canvas: {0}. Dispositivo de destino: {1}.', en: 'Create a Canvas: {0}. Target device: {1}.' },
	'openide.canvas.requestReady': { es: 'Tu selección está en el chat. Añadí los detalles que quieras y enviala cuando esté lista.', en: 'Your selection is in chat. Add any details and send it when ready.' },
	'openide.canvas.requestTitle': { es: 'Proyecto: {0}', en: 'Project: {0}' },
	'openide.canvas.rotation_x': { es: 'rotación X', en: 'rotation X' },
	'openide.canvas.rotation_y': { es: 'rotación Y', en: 'rotation Y' },
	'openide.canvas.rotation_z': { es: 'rotación Z', en: 'rotation Z' },
	'openide.canvas.save_comment': { es: 'Guardar comentario', en: 'Save comment' },
	'openide.canvas.save_keyframe': { es: 'Guardar fotograma clave', en: 'Save Keyframe' },
	'openide.canvas.scale_x': { es: 'escala X', en: 'scale X' },
	'openide.canvas.scale_y': { es: 'escala Y', en: 'scale Y' },
	'openide.canvas.scale_z': { es: 'escala Z', en: 'scale Z' },
	'openide.canvas.screen_title': { es: 'Título de la pantalla', en: 'Screen title' },
	'openide.canvas.select': { es: 'Seleccionar', en: 'Select' },
	'openide.canvas.shape': { es: 'Forma', en: 'Shape' },
	'openide.canvas.text': { es: 'Texto', en: 'Text' },
	'openide.canvas.time': { es: 'Tiempo', en: 'Time' },
	'openide.canvas.undo': { es: 'Deshacer', en: 'Undo' },
	'openide.canvas.viewport': { es: 'Área visible', en: 'Viewport' },
	'openide.canvas.whiteboard': { es: 'Pizarra', en: 'Whiteboard' },
	'openide.canvas.zoom': { es: 'Zoom', en: 'Zoom' },
	'openide.changes': { es: 'Cambios', en: 'Changes' },
	'openide.cli.launchFailed': { es: 'No se pudo iniciar {0}: {1}', en: 'Could not start {0}: {1}' },
	'openide.companion.terminal': { es: 'Usar terminal aquí', en: 'Use Terminal Here' },
	'openide.duration.minutes': { es: '{0}m {1}s', en: '{0}m {1}s' },
	'openide.duration.seconds': { es: '{0}s', en: '{0}s' },
	'openide.duration.worked': { es: 'Trabajó durante {0}', en: 'Worked for {0}' },
	'openide.duration.working': { es: 'Trabajando durante {0}', en: 'Working for {0}' },
	'openide.files.emptyDescription': { es: 'Elegí una carpeta para explorar sus archivos.', en: 'Choose a folder to browse its files.' },
	'openide.files.emptyTitle': { es: 'Abrir un proyecto', en: 'Open a project' },
	'openide.files.openFolder': { es: 'Abrir carpeta', en: 'Open folder' },
	'openide.requestAttachments': { es: 'Archivos adjuntos', en: 'Attached files' },
	'openide.requestPosition': { es: 'Solicitud {0} de {1}: {2}', en: 'Request {0} of {1}: {2}' },
	'openide.requestRail': { es: 'Solicitudes de la conversación', en: 'Conversation requests' },
	'openide.review.beforeAfter': { es: '{0} — Antes y después', en: '{0} — Before and After' },
	'openide.review.clear': { es: 'Limpiar filtro', en: 'Clear filter' },
	'openide.review.collapse': { es: 'Alternar {0}', en: 'Toggle {0}' },
	'openide.review.collapseAll': { es: 'Contraer todos los archivos', en: 'Collapse all files' },
	'openide.review.context': { es: 'Mostrar líneas sin cambios', en: 'Show unchanged lines' },
	'openide.review.deleted': { es: 'Archivo eliminado: {0}', en: 'Deleted file: {0}' },
	'openide.review.empty': { es: 'No hay cambios coincidentes', en: 'No matching changes' },
	'openide.review.emptyDescription': { es: 'Los cambios de tu proyecto aparecerán aquí.', en: 'Changes to your project will appear here.' },
	'openide.review.emptyFilter': { es: 'Probá con otro nombre de archivo o limpiá el filtro.', en: 'Try a different file name or clear the filter.' },
	'openide.review.expandAll': { es: 'Expandir archivos coincidentes', en: 'Expand matching files' },
	'openide.review.files': { es: '{0} archivos modificados', en: '{0} changed files' },
	'openide.review.filter': { es: 'Filtrar archivos…', en: 'Filter files…' },
	'openide.review.filtered': { es: '{0} de {1} archivos', en: '{0} of {1} files' },
	'openide.review.navigation': { es: 'Mostrar u ocultar árbol de archivos', en: 'Toggle file tree' },
	'openide.review.noChanges': { es: 'No hay cambios para revisar', en: 'No changes to review' },
	'openide.review.open': { es: 'Abrir archivo', en: 'Open file' },
	'openide.review.openComparison': { es: 'Abrir antes y después', en: 'Open Before and After' },
	'openide.review.openComparisonModal': { es: 'Abrir diff en modal', en: 'Open Diff in Modal' },
	'openide.review.partial': { es: 'parcial', en: 'partial' },
	'openide.review.partialTotals': { es: 'Recuentos de líneas disponibles para {0} de {1} archivos', en: 'Line counts available for {0} of {1} files' },
	'openide.review.save': { es: 'Guardar todo', en: 'Save all' },
	'openide.review.tree': { es: 'Archivos modificados', en: 'Changed files' },
	'openide.review.unavailable': { es: 'Vista previa no disponible. Abrí el archivo para inspeccionarlo.', en: 'Preview unavailable. Open the file to inspect it.' },
	'openide.sessions.clearFilters': { es: 'Limpiar filtros', en: 'Clear Filters' },
	'openide.sessions.projectActivity': { es: '{0} conversaciones · {1} activas', en: '{0} conversations · {1} active' },
	'openide.switch.agents': { es: 'Abrir en Agentes', en: 'Open in Agents' },
	'openide.switch.ide': { es: 'Abrir en IDE', en: 'Open in IDE' },
	'openide.whatsNew': { es: 'OpenIDE: Novedades', en: 'OpenIDE: What\'s New' },
	'openide.whatsNewUnavailable': { es: 'Los destacados de la versión no están disponibles. Revisá tu conexión e intentá de nuevo.', en: 'Release highlights are unavailable. Check your connection and try again.' },
} as const;
