/*---------------------------------------------------------------------------------------------
 *  Copyright (c) OpenIDE. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------
 *  OpenIDE — the marks of every provider models.dev publishes a logo for. GENERATED; the file to
 *  edit by hand is `openideProviderBranding.ts`, whose curated entries win over these.
 *
 *  Why it exists: the Providers page offers the whole registry now (openideModelCatalog.ts), and
 *  a list of 181 rows of two-letter monograms is a list nobody can scan. The ids are models.dev's
 *  own, so a provider added from the registry gets its mark with no mapping table.
 *
 *  `paint: 'full'` is set only where the logo carries its own colours (a gradient, more than one
 *  ink, or a mark sitting on a plate). Everything else is masked into the surface's ink like the
 *  curated marks, which is what makes a third-party logo read as part of the IDE.
 *
 *  Regenerating: download `https://models.dev/logos/<id>.svg` for every id in the registry, drop
 *  the ones that answer with the generic sparkle (models.dev returns it instead of a 404), strip
 *  scripts/external references, minify, and skip anything still over 20 KB — a logo that heavy is
 *  mush at 20 px anyway. See NOTICE.md beside the assets.
 *--------------------------------------------------------------------------------------------*/

import { IProviderBrand } from './openideProviderBranding.js';

/** models.dev provider id → its mark. Keys are exactly the registry's ids. */
export const OPENIDE_REGISTRY_PROVIDER_BRANDS: Readonly<Record<string, IProviderBrand>> = {
	'302ai': { name: '302.AI', initials: '3A', asset: 'registry/302ai.svg', paint: 'full' },
	'abacus': { name: 'Abacus', initials: 'AB', asset: 'registry/abacus.svg' },
	'above': { name: 'above.dev', initials: 'AD', asset: 'registry/above.svg' },
	'agentrouter': { name: 'AgentRouter', initials: 'AG', asset: 'registry/agentrouter.svg' },
	'agnes': { name: 'Agnes AI', initials: 'AA', asset: 'registry/agnes.svg' },
	'ai-router': { name: 'AI-ROUTER', initials: 'AR', asset: 'registry/ai-router.svg' },
	'aihubmix': { name: 'AIHubMix', initials: 'AI', asset: 'registry/aihubmix.svg' },
	'aixy': { name: 'Aixy', initials: 'AI', asset: 'registry/aixy.svg' },
	'aki-io': { name: 'AKI.IO', initials: 'AI', asset: 'registry/aki-io.svg' },
	'alibaba': { name: 'Alibaba', initials: 'AL', asset: 'registry/alibaba.svg' },
	'alibaba-cn': { name: 'Alibaba (China)', initials: 'AC', asset: 'registry/alibaba-cn.svg' },
	'alibaba-coding-plan': { name: 'Alibaba Coding Plan', initials: 'AC', asset: 'registry/alibaba-coding-plan.svg' },
	'alibaba-coding-plan-cn': { name: 'Alibaba Coding Plan (China)', initials: 'AC', asset: 'registry/alibaba-coding-plan-cn.svg' },
	'alibaba-token-plan': { name: 'Alibaba Token Plan', initials: 'AT', asset: 'registry/alibaba-token-plan.svg' },
	'amazon-bedrock': { name: 'Amazon Bedrock', initials: 'AB', asset: 'registry/amazon-bedrock.svg' },
	'ambient': { name: 'Ambient', initials: 'AM', asset: 'registry/ambient.svg' },
	'amd': { name: 'AMD', initials: 'AM', asset: 'registry/amd.svg' },
	'anyapi': { name: 'AnyAPI', initials: 'AN', asset: 'registry/anyapi.svg' },
	'arcee': { name: 'Arcee', initials: 'AR', asset: 'registry/arcee.svg' },
	'atomic-chat': { name: 'Atomic Chat', initials: 'AC', asset: 'registry/atomic-chat.svg' },
	'auriko': { name: 'Auriko', initials: 'AU', asset: 'registry/auriko.svg' },
	'azure': { name: 'Azure', initials: 'AZ', asset: 'registry/azure.svg' },
	'azure-cognitive-services': { name: 'Azure Cognitive Services', initials: 'AC', asset: 'registry/azure-cognitive-services.svg' },
	'bailing': { name: 'Bailing', initials: 'BA', asset: 'registry/bailing.svg' },
	'baseten': { name: 'Baseten', initials: 'BA', asset: 'registry/baseten.svg' },
	'berget': { name: 'Berget.AI', initials: 'BA', asset: 'registry/berget.svg' },
	'blueclaw': { name: 'Blue Claw', initials: 'BC', asset: 'registry/blueclaw.svg' },
	'bothub': { name: 'Bothub', initials: 'BO', asset: 'registry/bothub.svg' },
	'claudinio': { name: 'Claudinio', initials: 'CL', asset: 'registry/claudinio.svg' },
	'cloudferro-sherlock': { name: 'CloudFerro Sherlock', initials: 'CS', asset: 'registry/cloudferro-sherlock.svg' },
	'cloudflare-ai-gateway': { name: 'Cloudflare AI Gateway', initials: 'CA', asset: 'registry/cloudflare-ai-gateway.svg' },
	'cloudflare-workers-ai': { name: 'Cloudflare Workers AI', initials: 'CW', asset: 'registry/cloudflare-workers-ai.svg' },
	'coralbricks': { name: 'CoralBricks', initials: 'CO', asset: 'registry/coralbricks.svg' },
	'crossmodel': { name: 'CrossModel', initials: 'CR', asset: 'registry/crossmodel.svg' },
	'daoxe': { name: 'DaoXE', initials: 'DA', asset: 'registry/daoxe.svg' },
	'deepinfra': { name: 'Deep Infra', initials: 'DI', asset: 'registry/deepinfra.svg' },
	'digitalocean': { name: 'DigitalOcean', initials: 'DI', asset: 'registry/digitalocean.svg' },
	'dinference': { name: 'DInference', initials: 'DI', asset: 'registry/dinference.svg' },
	'ebcloud': { name: 'EBCloud', initials: 'EB', asset: 'registry/ebcloud.svg' },
	'echo': { name: 'Echo', initials: 'EC', asset: 'registry/echo.svg' },
	'edenai': { name: 'Eden AI', initials: 'EA', asset: 'registry/edenai.svg' },
	'empiriolabs': { name: 'EmpirioLabs AI', initials: 'EA', asset: 'registry/empiriolabs.svg' },
	'evroc': { name: 'evroc', initials: 'EV', asset: 'registry/evroc.svg' },
	'fastrouter': { name: 'FastRouter', initials: 'FA', asset: 'registry/fastrouter.svg' },
	'fireworks-ai': { name: 'Fireworks AI', initials: 'FA', asset: 'registry/fireworks-ai.svg' },
	'freemodel': { name: 'FreeModel', initials: 'FR', asset: 'registry/freemodel.svg' },
	'friendli': { name: 'Friendli', initials: 'FR', asset: 'registry/friendli.svg' },
	'frogbot': { name: 'FrogBot', initials: 'FR', asset: 'registry/frogbot.svg' },
	'github-copilot': { name: 'GitHub Copilot', initials: 'GC', asset: 'registry/github-copilot.svg' },
	'gitlab': { name: 'GitLab Duo', initials: 'GD', asset: 'registry/gitlab.svg' },
	'google': { name: 'Google', initials: 'GO', asset: 'registry/google.svg' },
	'google-vertex': { name: 'Vertex', initials: 'VE', asset: 'registry/google-vertex.svg' },
	'google-vertex-anthropic': { name: 'Vertex (Anthropic)', initials: 'VA', asset: 'registry/google-vertex-anthropic.svg' },
	'greenpt': { name: 'GreenPT', initials: 'GR', asset: 'registry/greenpt.svg' },
	'helicone': { name: 'Helicone', initials: 'HE', asset: 'registry/helicone.svg' },
	'hetzner': { name: 'Hetzner', initials: 'HE', asset: 'registry/hetzner.svg' },
	'huggingface': { name: 'Hugging Face', initials: 'HF', asset: 'registry/huggingface.svg' },
	'hyper': { name: 'Charm Hyper', initials: 'CH', asset: 'registry/hyper.svg' },
	'iflowcn': { name: 'iFlow', initials: 'IF', asset: 'registry/iflowcn.svg' },
	'impossibl': { name: 'Impossibl', initials: 'IM', asset: 'registry/impossibl.svg' },
	'inception': { name: 'Inception', initials: 'IN', asset: 'registry/inception.svg' },
	'inceptron': { name: 'Inceptron', initials: 'IN', asset: 'registry/inceptron.svg' },
	'inference': { name: 'Inference', initials: 'IN', asset: 'registry/inference.svg' },
	'inferx': { name: 'InferX', initials: 'IN', asset: 'registry/inferx.svg' },
	'infomaniak': { name: 'Infomaniak', initials: 'IN', asset: 'registry/infomaniak.svg' },
	'io-net': { name: 'IO.NET', initials: 'IN', asset: 'registry/io-net.svg' },
	'iteracompute': { name: 'IteraCompute', initials: 'IT', asset: 'registry/iteracompute.svg' },
	'jalapeno': { name: 'Jalapeno Cloud', initials: 'JC', asset: 'registry/jalapeno.svg' },
	'jiekou': { name: 'Jiekou.AI', initials: 'JA', asset: 'registry/jiekou.svg' },
	'kenari': { name: 'Kenari', initials: 'KE', asset: 'registry/kenari.svg' },
	'kilo': { name: 'Kilo Gateway', initials: 'KG', asset: 'registry/kilo.svg' },
	'kimi-for-coding': { name: 'Kimi For Coding', initials: 'KF', asset: 'registry/kimi-for-coding.svg' },
	'klokintegration': { name: 'klokintegration.se', initials: 'KS', asset: 'registry/klokintegration.svg' },
	'kuae-cloud-coding-plan': { name: 'KUAE Cloud Coding Plan', initials: 'KC', asset: 'registry/kuae-cloud-coding-plan.svg' },
	'lilac': { name: 'Lilac', initials: 'LI', asset: 'registry/lilac.svg' },
	'llama': { name: 'Llama', initials: 'LL', asset: 'registry/llama.svg' },
	'llmgateway': { name: 'DevPass (LLM Gateway)', initials: 'DL', asset: 'registry/llmgateway.svg' },
	'llmgateway-providers': { name: 'LLM Gateway', initials: 'LG', asset: 'registry/llmgateway-providers.svg' },
	'llmtech': { name: 'LLM Tech', initials: 'LT', asset: 'registry/llmtech.svg' },
	'llmtr': { name: 'LLMTR', initials: 'LL', asset: 'registry/llmtr.svg' },
	'longcat': { name: 'LongCat', initials: 'LO', asset: 'registry/longcat.svg' },
	'lynkr': { name: 'Lynkr', initials: 'LY', asset: 'registry/lynkr.svg' },
	'meganova': { name: 'Meganova', initials: 'ME', asset: 'registry/meganova.svg' },
	'merge-gateway': { name: 'Merge Gateway', initials: 'MG', asset: 'registry/merge-gateway.svg' },
	'meta': { name: 'Meta', initials: 'ME', asset: 'registry/meta.svg' },
	'minimax-cn': { name: 'MiniMax (minimaxi.com)', initials: 'MM', asset: 'registry/minimax-cn.svg' },
	'minimax-cn-coding-plan': { name: 'MiniMax Token Plan (minimaxi.com)', initials: 'MT', asset: 'registry/minimax-cn-coding-plan.svg' },
	'minimax-coding-plan': { name: 'MiniMax Token Plan (minimax.io)', initials: 'MT', asset: 'registry/minimax-coding-plan.svg' },
	'mixlayer': { name: 'Mixlayer', initials: 'MI', asset: 'registry/mixlayer.svg' },
	'moark': { name: 'Moark', initials: 'MO', asset: 'registry/moark.svg' },
	'modal': { name: 'Modal', initials: 'MO', asset: 'registry/modal.svg' },
	'model-oracle-ai': { name: 'Model Oracle AI', initials: 'MO', asset: 'registry/model-oracle-ai.svg' },
	'modelis': { name: 'Modelis', initials: 'MO', asset: 'registry/modelis.svg' },
	'modelscope': { name: 'ModelScope', initials: 'MO', asset: 'registry/modelscope.svg' },
	'moonshotai': { name: 'Moonshot AI', initials: 'MA', asset: 'registry/moonshotai.svg' },
	'moonshotai-cn': { name: 'Moonshot AI (China)', initials: 'MA', asset: 'registry/moonshotai-cn.svg' },
	'nan': { name: 'NaN', initials: 'NA', asset: 'registry/nan.svg' },
	'nano-gpt': { name: 'NanoGPT', initials: 'NA', asset: 'registry/nano-gpt.svg' },
	'nearai': { name: 'NEAR AI Cloud', initials: 'NA', asset: 'registry/nearai.svg' },
	'nebius': { name: 'Nebius Token Factory', initials: 'NT', asset: 'registry/nebius.svg' },
	'neon': { name: 'Neon', initials: 'NE', asset: 'registry/neon.svg' },
	'neosmith': { name: 'NeoSmith', initials: 'NE', asset: 'registry/neosmith.svg' },
	'neuralwatt': { name: 'Neuralwatt', initials: 'NE', asset: 'registry/neuralwatt.svg' },
	'nova': { name: 'Nova', initials: 'NO', asset: 'registry/nova.svg' },
	'novita-ai': { name: 'NovitaAI', initials: 'NO', asset: 'registry/novita-ai.svg' },
	'nvidia': { name: 'Nvidia', initials: 'NV', asset: 'registry/nvidia.svg' },
	'ofox': { name: 'Ofox', initials: 'OF', asset: 'registry/ofox.svg' },
	'ollama-cloud': { name: 'Ollama Cloud', initials: 'OC', asset: 'registry/ollama-cloud.svg' },
	'opencode-go': { name: 'OpenCode Go', initials: 'OG', asset: 'registry/opencode-go.svg' },
	'openreason': { name: 'OpenReason', initials: 'OP', asset: 'registry/openreason.svg' },
	'opper': { name: 'Opper', initials: 'OP', asset: 'registry/opper.svg' },
	'orcarouter': { name: 'OrcaRouter', initials: 'OR', asset: 'registry/orcarouter.svg' },
	'ovhcloud': { name: 'OVHcloud AI Endpoints', initials: 'OA', asset: 'registry/ovhcloud.svg' },
	'pendra': { name: 'Pendra', initials: 'PE', asset: 'registry/pendra.svg' },
	'perplexity-agent': { name: 'Perplexity Agent', initials: 'PA', asset: 'registry/perplexity-agent.svg' },
	'pioneer': { name: 'Pioneer', initials: 'PI', asset: 'registry/pioneer.svg' },
	'poe': { name: 'Poe', initials: 'PO', asset: 'registry/poe.svg' },
	'poolside': { name: 'Poolside', initials: 'PO', asset: 'registry/poolside.svg' },
	'privatemode-ai': { name: 'Privatemode AI', initials: 'PA', asset: 'registry/privatemode-ai.svg' },
	'qihang-ai': { name: 'QiHang', initials: 'QI', asset: 'registry/qihang-ai.svg' },
	'qiniu-ai': { name: 'Qiniu', initials: 'QI', asset: 'registry/qiniu-ai.svg' },
	'qvac': { name: 'QVAC', initials: 'QV', asset: 'registry/qvac.svg' },
	'regolo-ai': { name: 'Regolo AI', initials: 'RA', asset: 'registry/regolo-ai.svg', paint: 'full' },
	'routing-run': { name: 'routing.run', initials: 'RR', asset: 'registry/routing-run.svg' },
	'runinfra': { name: 'RunInfra', initials: 'RU', asset: 'registry/runinfra.svg' },
	'salad-cloud': { name: 'SaladCloud AI Gateway', initials: 'SA', asset: 'registry/salad-cloud.svg' },
	'scaleway': { name: 'Scaleway', initials: 'SC', asset: 'registry/scaleway.svg' },
	'scx-ai': { name: 'SCX.ai', initials: 'SA', asset: 'registry/scx-ai.svg' },
	'sensenova': { name: 'SenseNova (China)', initials: 'SC', asset: 'registry/sensenova.svg' },
	'siliconflow': { name: 'SiliconFlow', initials: 'SI', asset: 'registry/siliconflow.svg' },
	'siliconflow-cn': { name: 'SiliconFlow (China)', initials: 'SC', asset: 'registry/siliconflow-cn.svg' },
	'snowflake-cortex': { name: 'Snowflake Cortex', initials: 'SC', asset: 'registry/snowflake-cortex.svg' },
	'stackit': { name: 'STACKIT', initials: 'ST', asset: 'registry/stackit.svg' },
	'standardcompute': { name: 'Standard Compute', initials: 'SC', asset: 'registry/standardcompute.svg' },
	'stepfun': { name: 'StepFun (China)', initials: 'SC', asset: 'registry/stepfun.svg' },
	'stepfun-ai': { name: 'StepFun (Global)', initials: 'SG', asset: 'registry/stepfun-ai.svg' },
	'stepfun-ai-step-plan': { name: 'StepFun Step Plan (Global)', initials: 'SS', asset: 'registry/stepfun-ai-step-plan.svg' },
	'stepfun-step-plan': { name: 'StepFun Step Plan (China)', initials: 'SS', asset: 'registry/stepfun-step-plan.svg' },
	'subconscious': { name: 'Subconscious', initials: 'SU', asset: 'registry/subconscious.svg' },
	'submodel': { name: 'submodel', initials: 'SU', asset: 'registry/submodel.svg' },
	'tencent-coding-plan': { name: 'Tencent Coding Plan (China)', initials: 'TC', asset: 'registry/tencent-coding-plan.svg' },
	'tencent-token-plan': { name: 'Tencent Token Plan', initials: 'TT', asset: 'registry/tencent-token-plan.svg' },
	'tencent-tokenhub': { name: 'Tencent TokenHub', initials: 'TT', asset: 'registry/tencent-tokenhub.svg' },
	'tensorx': { name: 'TensorX', initials: 'TE', asset: 'registry/tensorx.svg' },
	'the-grid-ai': { name: 'The Grid AI', initials: 'TG', asset: 'registry/the-grid-ai.svg' },
	'thinkingmachines': { name: 'Thinking Machines', initials: 'TM', asset: 'registry/thinkingmachines.svg' },
	'tinfoil': { name: 'Tinfoil', initials: 'TI', asset: 'registry/tinfoil.svg' },
	'togetherai': { name: 'Together AI', initials: 'TA', asset: 'registry/togetherai.svg' },
	'tokengo': { name: 'TokenGo', initials: 'TO', asset: 'registry/tokengo.svg' },
	'tokenrouter': { name: 'TokenRouter', initials: 'TO', asset: 'registry/tokenrouter.svg' },
	'trustedrouter': { name: 'TrustedRouter', initials: 'TR', asset: 'registry/trustedrouter.svg' },
	'umans-ai': { name: 'Umans AI', initials: 'UA', asset: 'registry/umans-ai.svg' },
	'umans-ai-coding-plan': { name: 'Umans AI Coding Plan', initials: 'UA', asset: 'registry/umans-ai-coding-plan.svg' },
	'unorouter': { name: 'UnoRouter', initials: 'UN', asset: 'registry/unorouter.svg' },
	'v0': { name: 'v0', initials: 'V0', asset: 'registry/v0.svg' },
	'vancine': { name: 'Vancine', initials: 'VA', asset: 'registry/vancine.svg' },
	'venice': { name: 'Venice AI', initials: 'VA', asset: 'registry/venice.svg' },
	'vercel': { name: 'Vercel AI Gateway', initials: 'VA', asset: 'registry/vercel.svg' },
	'vivgrid': { name: 'Vivgrid', initials: 'VI', asset: 'registry/vivgrid.svg' },
	'volcengine': { name: 'Volcengine Ark', initials: 'VA', asset: 'registry/volcengine.svg' },
	'volcengine-coding-plan': { name: 'Volcengine Ark Coding Plan', initials: 'VA', asset: 'registry/volcengine-coding-plan.svg' },
	'vultr': { name: 'Vultr', initials: 'VU', asset: 'registry/vultr.svg' },
	'wafer.ai': { name: 'Wafer', initials: 'WA', asset: 'registry/wafer.ai.svg' },
	'watsonx': { name: 'watsonx.ai', initials: 'WA', asset: 'registry/watsonx.svg' },
	'xiaomi': { name: 'Xiaomi', initials: 'XI', asset: 'registry/xiaomi.svg' },
	'xiaomi-token-plan-ams': { name: 'Xiaomi Token Plan (Europe)', initials: 'XT', asset: 'registry/xiaomi-token-plan-ams.svg' },
	'xiaomi-token-plan-cn': { name: 'Xiaomi Token Plan (China)', initials: 'XT', asset: 'registry/xiaomi-token-plan-cn.svg' },
	'xiaomi-token-plan-sgp': { name: 'Xiaomi Token Plan (Singapore)', initials: 'XT', asset: 'registry/xiaomi-token-plan-sgp.svg' },
	'xpersona': { name: 'Xpersona', initials: 'XP', asset: 'registry/xpersona.svg' },
	'zai': { name: 'Z.AI', initials: 'ZA', asset: 'registry/zai.svg' },
	'zai-coding-plan': { name: 'Z.AI Coding Plan', initials: 'ZA', asset: 'registry/zai-coding-plan.svg' },
	'zeldoc': { name: 'Zeldoc', initials: 'ZE', asset: 'registry/zeldoc.svg' },
	'zenifra': { name: 'Zenifra', initials: 'ZE', asset: 'registry/zenifra.svg' },
	'zenmux': { name: 'ZenMux', initials: 'ZE', asset: 'registry/zenmux.svg' },
	'zhipuai': { name: 'Zhipu AI', initials: 'ZA', asset: 'registry/zhipuai.svg' },
	'zhipuai-coding-plan': { name: 'Zhipu AI Coding Plan', initials: 'ZA', asset: 'registry/zhipuai-coding-plan.svg' },
};
