/*---------------------------------------------------------------------------------------------
 *  Copyright (c) OpenIDE. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/** Provider setup and connection status shown in the workbench. */
export const OPENIDE_PROVIDER_STRINGS = {
	'openide.invalidApiKey': { es: 'Ingresá una clave API sin espacios ni saltos de línea.', en: 'Enter an API key without spaces or line breaks.' },
	'openide.chat.history.unreadable': { es: 'No se pudo leer el historial de esta conversación. Los datos guardados se conservaron.', en: 'Could not read this conversation history. Saved data was preserved.' },
	'openide.chat.archive.unreadable': { es: 'No se pudo leer una parte archivada de esta conversación. Los datos guardados se conservaron.', en: 'Could not read an archived part of this conversation. Saved data was preserved.' },
	'openide.duplicateProvider': { es: 'Ya existe un proveedor con este identificador.', en: 'A provider with this identifier already exists.' },
	'openide.missingCustomProvider': { es: 'Este proveedor personalizado ya no existe.', en: 'This custom provider no longer exists.' },
	'openide.providerSetup.edit': { es: 'Editar proveedor', en: 'Edit provider' },
	'openide.providerSetup.add': { es: 'Agregar proveedor', en: 'Add provider' },
	'openide.providerSetup.intro': { es: 'Conectá tu propia API o un servidor local de modelos. Podés guardar el proveedor ahora y agregar una clave después.', en: 'Connect your own API or a local model server. You can save the provider now and add a key later.' },
	'openide.providerSetup.name': { es: 'Nombre del proveedor', en: 'Provider name' },
	'openide.providerSetup.nameHelp': { es: 'El nombre que aparece en el selector de modelos.', en: 'The name shown in the model picker.' },
	'openide.providerSetup.namePlaceholder': { es: 'Mi proveedor', en: 'My provider' },
	'openide.providerSetup.id': { es: 'Identificador', en: 'Identifier' },
	'openide.providerSetup.idFixed': { es: 'Se mantiene para que las cuentas y conversaciones guardadas sigan vinculadas.', en: 'Kept unchanged so saved accounts and conversations stay linked.' },
	'openide.providerSetup.idHelp': { es: 'Se crea a partir del nombre. Podés cambiarlo antes de guardar.', en: 'Created from the name. You can customize it before saving.' },
	'openide.providerSetup.endpoint': { es: 'URL base', en: 'Base URL' },
	'openide.providerSetup.endpointHelp': { es: 'Usá la dirección base de la API, incluido /v1 si tu servidor lo requiere.', en: 'Use the API base address, including /v1 if your server requires it.' },
	'openide.providerSetup.protocol': { es: 'Formato de API', en: 'API format' },
	'openide.providerSetup.protocolHelp': { es: 'Elegí la API que implementa tu servidor.', en: 'Choose the API your server implements.' },
	'openide.providerSetup.completions': { es: 'Compatible con OpenAI · Chat Completions', en: 'OpenAI compatible · Chat Completions' },
	'openide.providerSetup.responses': { es: 'Compatible con OpenAI · Responses', en: 'OpenAI compatible · Responses' },
	'openide.providerSetup.anthropic': { es: 'Anthropic · Messages', en: 'Anthropic · Messages' },
	'openide.providerSetup.auth': { es: 'Autenticación', en: 'Authentication' },
	'openide.providerSetup.authHelp': { es: 'Los servidores locales suelen funcionar sin clave.', en: 'Local servers often work without a key.' },
	'openide.providerSetup.authKey': { es: 'Clave API', en: 'API key' },
	'openide.providerSetup.authNone': { es: 'Sin autenticación', en: 'No authentication' },
	'openide.providerSetup.key': { es: 'Clave API (opcional)', en: 'API key (optional)' },
	'openide.providerSetup.keyKeep': { es: 'Dejá el campo vacío para conservar la clave actual. Las claves nuevas se guardan en el almacén seguro, por separado de los ajustes.', en: 'Leave empty to keep the current key. New keys are saved in the secret store, separately from settings.' },
	'openide.providerSetup.keyHelp': { es: 'Se guarda en el almacén seguro, por separado de los ajustes. También podés agregarla después.', en: 'Saved in the secret store, separately from settings. You can also add it later.' },
	'openide.providerSetup.showKey': { es: 'Mostrar', en: 'Show' },
	'openide.providerSetup.showKeyLabel': { es: 'Mostrar clave API', en: 'Show API key' },
	'openide.providerSetup.hideKey': { es: 'Ocultar', en: 'Hide' },
	'openide.providerSetup.hideKeyLabel': { es: 'Ocultar clave API', en: 'Hide API key' },
	'openide.providerSetup.model': { es: 'Modelo predeterminado (opcional)', en: 'Default model (optional)' },
	'openide.providerSetup.modelHelp': { es: 'Ingresá el ID exacto de un modelo o elegí uno detectado después de conectar.', en: 'Enter an exact model ID, or choose a discovered model after connecting.' },
	'openide.providerSetup.check': { es: 'Probar conexión', en: 'Test connection' },
	'openide.providerSetup.saveUnchecked': { es: 'Guardar sin verificar', en: 'Save without checking' },
	'openide.providerSetup.cancel': { es: 'Cancelar', en: 'Cancel' },
	'openide.providerSetup.save': { es: 'Guardar cambios', en: 'Save changes' },
	'openide.providerSetup.anthropicEndpointHelp': { es: 'Usá la dirección anterior a /v1/messages, por ejemplo https://api.anthropic.com. OpenIDE agrega /v1 para este formato de API.', en: 'Use the address before /v1/messages, for example https://api.anthropic.com. OpenIDE adds /v1 for this API format.' },
	'openide.providerSetup.saving': { es: 'Guardando…', en: 'Saving…' },
	'openide.providerSetup.checking': { es: 'Probando…', en: 'Testing…' },
	'openide.providerSetup.checkWait': { es: 'Verificando el endpoint y el acceso a los modelos…', en: 'Checking the endpoint and model access…' },
	'openide.providerSetup.saved': { es: 'Proveedor guardado.', en: 'Provider saved.' },
	'openide.providerSetup.saveFailed': { es: 'No se pudo guardar el proveedor. Los datos que ingresaste siguen aquí; intentá de nuevo.', en: 'Could not save the provider. Your entries are still here; try again.' },
	'openide.providerSetup.checkFailed': { es: 'No se pudo conectar al proveedor. Revisá la dirección e intentá de nuevo.', en: 'Could not reach the provider. Check the address and try again.' },
	'openide.providerSetup.nameRequired': { es: 'Ingresá un nombre para el proveedor.', en: 'Enter a provider name.' },
	'openide.providerSetup.idInvalid': { es: 'Empezá con una letra y usá solo letras, números, puntos, guiones bajos o guiones.', en: 'Start with a letter and use only letters, numbers, dots, underscores or dashes.' },
	'openide.providerSetup.idExists': { es: 'Este identificador pertenece a otro proveedor. Elegí uno diferente.', en: 'This identifier belongs to another provider. Choose a different one.' },
	'openide.providerSetup.idImmutable': { es: 'Conservá el identificador actual para mantener las cuentas guardadas.', en: 'Keep the existing identifier to preserve saved accounts.' },
	'openide.providerSetup.urlRequired': { es: 'Ingresá la URL base de la API.', en: 'Enter the API base URL.' },
	'openide.providerSetup.urlInvalid': { es: 'Ingresá una dirección HTTP o HTTPS completa.', en: 'Enter a complete HTTP or HTTPS address.' },
	'openide.providerSetup.urlCredentials': { es: 'Quitá las credenciales de la dirección y usá el campo de clave API.', en: 'Remove credentials from the address and use the API key field.' },
	'openide.providerSetup.urlQuery': { es: 'Usá la dirección base de la API sin parámetros de consulta ni fragmentos.', en: 'Use the API base address without query parameters or a fragment.' },
	'openide.providerSetup.keyInvalid': { es: 'Pegá solo la clave, sin espacios, saltos de línea ni el prefijo Bearer.', en: 'Paste only the key, without spaces, line breaks or a Bearer prefix.' },
	'openide.provider.check.available': { es: 'Conexión verificada · {0} modelos disponibles', en: 'Connection verified · {0} models available' },
	'openide.provider.check.empty': { es: 'Conexión verificada. El servidor todavía no tiene modelos cargados.', en: 'Connection verified. The server has no models loaded yet.' },
	'openide.provider.check.unverified': { es: 'Este proveedor no permite una prueba de conexión compatible. Podés guardar la configuración y elegir un modelo manualmente.', en: 'This provider does not offer a compatible connection check. You can save the configuration and choose a model manually.' },
	'openide.provider.check.missing': { es: 'Agregá una clave API o iniciá sesión antes de probar esta conexión.', en: 'Add an API key or sign in before checking this connection.' },
	'openide.provider.check.auth': { es: 'El proveedor rechazó esta credencial. Revisá la clave API y sus permisos; la clave guardada no cambió.', en: 'The provider rejected this credential. Check the API key and its permissions; your saved key has not been changed.' },
	'openide.provider.check.endpoint': { es: 'El proveedor no pudo completar la prueba (HTTP {0}). Revisá el endpoint o intentá más tarde.', en: 'The provider could not complete the check (HTTP {0}). Check the endpoint or try again later.' },
	'openide.provider.check.unreachable': { es: 'No se pudo conectar al proveedor. Revisá la URL, la red o si el servidor local está en ejecución.', en: 'Could not reach the provider. Check the URL, network connection, or whether the local server is running.' },
	'openide.providers.detect': { es: 'Actualizar detección', en: 'Refresh detection' },
	'openide.providers.configured': { es: 'Configurados', en: 'Configured' },
	'openide.providers.keyAvailable': { es: 'Clave API disponible', en: 'API key available' },
	'openide.providers.edit': { es: 'Editar proveedor', en: 'Edit provider' },
	'openide.providers.check': { es: 'Probar conexión', en: 'Test connection' },
	'openide.providers.showKey': { es: 'Mostrar clave API', en: 'Show API key' },
	'openide.providers.hideKey': { es: 'Ocultar clave API', en: 'Hide API key' },
	'openide.providers.checking': { es: 'Verificando…', en: 'Checking…' },
	'openide.providers.saveUnchecked': { es: 'Guardar sin verificar', en: 'Save without checking' },
	'openide.providers.checkFailed': { es: 'No se pudo verificar la conexión. Intentá de nuevo.', en: 'Could not check the connection. Try again.' },
	'openide.providers.keySavedUnverified': { es: 'Clave API guardada para {0}. La conexión aún no se verificó.', en: 'API key saved for {0}. The connection has not been verified.' },
	'openide.providers.keySaveFailed': { es: 'No se pudo guardar la clave API. Revisá el almacén seguro e intentá de nuevo.', en: 'Could not save the API key. Check secret storage and try again.' },
	'openide.providers.draftRejected': { es: 'Clave nueva rechazada', en: 'New key rejected' },
	'openide.providers.rejected': { es: 'Credencial rechazada', en: 'Credential rejected' },
	'openide.providers.offline': { es: 'Servidor no disponible', en: 'Server unavailable' },
} as const satisfies Record<string, { es: string; en: string }>;
